### ISSUE TITLE
Different background colors between vim, neovim and neovim in tmux

### ISSUE THREAD

**Issue by ysomad** [mhartington/oceanic-next#104]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
1.Different background colors in vim and neovim
2. Different background colors in neovim when in tmux

## Expected
Wanna set dark background from vim to neovim

## Environment Information

 * terminal: gnome-terminal
 * vim/nvim version: vim (8.1.2269), nvim (v0.5.0-dev+1157-g0ab88c2ea)

## Provide a minimal vim rc with less than 50 lines (Required!)

vimrc: https://gist.github.com/Infvmous/8e71e7631a6828f5fcd1e58ed6f210a1
init.vim: https://gist.github.com/Infvmous/6a1ade341f59def2ac1adbe9abb4fbc8

## Screen shot (if possible)

[vim](https://imgur.com/a/WwI38OQ)
[neovim](https://imgur.com/a/xU4J16I)
[neovim in tmux](https://imgur.com/a/F8pqpAQ)

**Comment by mhartington** [comment]
Please note the install instructions 

https://github.com/mhartington/oceanic-next#installation


```
" Theme
 syntax enable
" for vim 7
 set t_Co=256

" for vim 8
 if (has("termguicolors"))
  set termguicolors
 endif

colorscheme OceanicNext
```

You're missing termguicolors.

For tmux, you need to enable true colors for tmux.
