### ISSUE TITLE
Oceanic Next on Neovim Incorrect Color 

### ISSUE THREAD

**Issue by cusxio** [mhartington/oceanic-next#11]
![screen shot 2016-01-08 at 1 03 54 am](https://cloud.githubusercontent.com/assets/6487613/12176791/084ddbb0-b5a4-11e5-97fb-4620675f00a3.png)

Configuration straight from the manual:

```
 syntax enable
 let $NVIM_TUI_ENABLE_TRUE_COLOR=1
 colorscheme OceanicNext
 set background=dark
```

I have used/ set all the Options in my nvimrc, and I am using iTerm 2 Nightly Build too.
What might be some of the reason for this to happen? I am fairly new to Vim/Neovim in general.

**Comment by mhartington** [comment]
Looks like you're using the jsx syntax plugin, correct? 
Do you have a minimal init.vim I could look at? 

Other that the syntax, everything else looks to be loading correctly. It's probably just the jsx plugin

**Comment by cusxio** [comment]
```
call plug#begin('~/.config/nvim/plugged')
Plug 'pangloss/vim-javascript', {'for': ['javascript']}
Plug 'mxw/vim-jsx', {'for': ['javascript']}
Plug 'othree/yajs.vim', {'for': ['javascript']}
Plug 'othree/javascript-libraries-syntax.vim', {'for': ['javascript']}
Plug 'mhartington/oceanic-next'
call plug#end()
syntax enable
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
colorscheme OceanicNext
set background=dark
```

This is the most minimal version I could get to create the issue.
`vim-jsx` is requires `pangloss/vim-javascript` so both these packages goes hand in hand.

Once I remove those packages, the color schemes works perfectly.
