### ISSUE TITLE
Support highlight groups

### ISSUE THREAD

**Issue by aktau** [mhartington/oceanic-next#112]
(This is a feature request rather than a bug report so I didn't fill in all of the sections, please do advise.)

# Problems summary

mhartington/oceanic-next does not support highlight groups (used by e.g. nvim-lsp when the LSP supports highlighting functionality).

The functionality, and oceanic-next's lack of support for it, was documented on https://sbulav.github.io/til/til-neovim-highlight-references/.

## Expected

I'd expect it to support it like https://github.com/folke/tokyonight.nvim, https://github.com/ellisonleao/gruvbox.nvim, https://github.com/rebelot/kanagawa.nvim et cetera, if that is reasonable to do as a dual editor colorscheme (classic Vim and Neovim).

**Comment by mhartington** [comment]
Hey, sorry for not getting to this sooner (life happens).

But this should be supported with the latest release

<img width="612" alt="Screenshot 2023-05-01 at 8 51 12 AM" src="https://user-images.githubusercontent.com/2835826/235461268-18b25ca8-6612-46f9-a171-2c5af638e06a.png">

**Comment by aktau** [comment]
Thanks a lot, I'll check it out sometime soon.
