### ISSUE TITLE
XML syntax uses `xmlTagN` rather than `xmlTagName`

### ISSUE THREAD

**Issue by binyomen** [mhartington/oceanic-next#114]
# Problems summary
XML syntax is defined using `xmlTagN` rather than `xmlTagName` in `after/syntax/xml.vim`.

## Expected
This syntax should use the well-known highlight group `xmlTagName`.

## Environment Information

 * terminal: Reproed in both terminal (Windows Terminal) and GUI (neovide 0.8.0)
 * vim/nvim version: nvim 0.7.2

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/oceanic-next
colorscheme OceanicNext
```

## The reproduce ways from neovim starting

 1. open an XML file
 2. notice that the end tags (`</example>`) are highlighted using `xmlTagN` rather than `xmlTagName`.

**Comment by jsit** [comment]
@mhartington It strikes me as odd that this color scheme is redefining a syntax match to begin with? It seems like this should be a bug filed against [chrisbra/vim-xml-runtime](https://github.com/chrisbra/vim-xml-runtime) if there is indeed an issue with this syntax. I didn't have this bugfix in my latest pull and I wondered why XML closing tag highlighting was broken.
