### ISSUE TITLE
With the recent update, it's broken with vim

### ISSUE THREAD

**Issue by mrpeabody** [mhartington/oceanic-next#118]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

Simply start vim to get the following issue:

```
Error detected while processing /home/mrpeabody/.vimrc[456]../home/mrpeabody/.vim/plugged/oceanic-next/colors/OceanicNext.vim[36]..function oceanic_next#highlight[243]..<SNR>31_hi:
line    3:
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
Press ENTER or type command to continue
```

Confirmed to be broken on both macOS and Linux.

## Expected

To work, as before.

## Environment Information

 * terminal:
 * vim/nvim version: VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 25 2023 00:00:00)

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/oceanic-next
colorscheme OceanicNext
```

## The reproduce ways from neovim starting

 1. modify vimrc to use `OceanicNext` colorscheme
 2. start vim
 3. bingo

## Screen shot (if possible)

![image](https://user-images.githubusercontent.com/438981/235458151-2fa08965-7b20-4d2c-984c-c18758a15619.png)

**Comment by mhartington** [comment]
Thanks for the heads up! Looks like vim doesn't like the new treesitter syntax happening in neovim. Should be fixed now.

**Comment by mrpeabody** [comment]
Thank you, works great now!
