### ISSUE TITLE
OceanNext in Neovim showing wrong colours

### ISSUE THREAD

**Issue by pdoak** [mhartington/oceanic-next#12]
Hi

I have just installed Neovim and watched your [https://www.youtube.com/watch?v=xZTkrB_tEoY](youTube) video and am trying to get your oceanic next to work. I have set up a minimum init.vim as per another user who was struggling but it still does not work.

This is the colour scheme that it produces:
![screen shot 2016-01-12 at 14 22 16](https://cloud.githubusercontent.com/assets/1565586/12266276/2bf41ef0-b93a-11e5-80f2-02d2e186eee8.png)

The only plugin loaded is the oceanic-next one and it still does not work. I am using iTerm Build 2.9.20160112-nightly on Mac os x 10.11.2. I have selected 14pt Inconoloata for Powerline as the text in iTerm2.

Any help appreciated.

**Comment by mhartington** [comment]
So unfortunately, youtube doesn't messes with the color once it's uploaded. So if you're looking for that greenish color, it's a problem on youtube's end. 

As for the colors not loading, I created a minimal init.vim

``` vim
call plug#begin('~/.config/nvim/plugged')
Plug 'mhartington/oceanic-next'
Plug 'othree/yajs.vim'
call plug#end()
syntax enable
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
colorscheme OceanicNext
set background=dark
```

And things looked fine to me. 

<img width="828" alt="screen shot 2016-01-12 at 7 43 16 am" src="https://cloud.githubusercontent.com/assets/2835826/12268128/508bfeac-b900-11e5-90a4-39cc0fe5f152.png">

A quick way to test is to git clone the project, and open test.js. This is my comparison file to the original theme. Here's the test.js file with the same minimal rc file.

<img width="736" alt="screen shot 2016-01-12 at 7 45 25 am" src="https://cloud.githubusercontent.com/assets/2835826/12268177/84c77f3e-b900-11e5-87d2-249d48239cb0.png">

**Comment by pdoak** [comment]
My test.js looks exactly the same as yours. The reason I thought is was not working was because your init.vim colours look like this on youTube:
![screen shot 2016-01-12 at 15 59 21](https://cloud.githubusercontent.com/assets/1565586/12268676/aac03b6e-b945-11e5-980a-7d10b30df2dc.png)

This looks very different to the reds and yellows from your screen shot above. 

Thanks for the quick response - I now know that it is working properly. Just have to get vim-airline showing the glyphs now!

**Comment by mhartington** [comment]
yeah, youtube likes to muck around with colors :disappointed: 
Closing.
