### ISSUE TITLE
Colors are not displayed properly

### ISSUE THREAD

**Issue by majjoha** [mhartington/oceanic-next#13]
Similar to other issues in this repository, I cannot display this theme correctly.

I am running Neovim version 0.1.1, and iTerm 2 (Build 2.9.20160112-nightly) with the following minimal `.vimrc`:

``` vim
set runtimepath+=~/.env/.vim
execute pathogen#infect()
call pathogen#helptags()
syntax enable
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
colorscheme OceanicNext
set background=dark
```

Please, note that I am using pathogen, and the repository is added as a submodule in `~/.env/.vim/bundle`.

The `test.js` file is displayed as such:
<img width="1322" alt="screen shot 2016-01-13 at 19 02 30" src="https://cloud.githubusercontent.com/assets/233988/12302974/41b7876a-ba28-11e5-8126-a6a134a0c672.png">

Any help would be useful!

**Comment by mhartington** [comment]
Hmm I have not tested pathogen....so this could be a legit issue. 
Will investigate. Thanks

**Comment by mhartington** [comment]
Hmm, it could be the RTP setup.

```
execute pathogen#infect('~/.config/nvim/bundle/{}')
call pathogen#helptags()
syntax enable
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
colorscheme OceanicNext
set background=dark
```

Where my `~/.config/nvim` directory looks like such 

```
.
├── autoload
│   └── pathogen.vim
├── bundle
│   ├── oceanic-next
│   │   ├── README.md
│   │   ├── autoload
│   │   │   └── airline
│   │   │       └── themes
│   │   │           └── oceanicnext.vim
│   │   ├── colors
│   │   │   └── OceanicNext.vim
│   │   ├── license.txt
│   │   ├── oceanic-next-dark.nvim.png
│   │   ├── oceanic-next-dark.vim.png
│   │   ├── test.css
│   │   └── test.js
│   └── vim-sensible
│       ├── README.markdown
│       └── plugin
│           └── sensible.vim
└── init.vim
```

And when I open the test.js file
_the colors aren't 100% to the screen shot since I don't have the proper syntax plugin_

<img width="697" alt="screen shot 2016-01-13 at 12 03 40 pm" src="https://cloud.githubusercontent.com/assets/2835826/12306275/bebdfae0-b9ed-11e5-9be5-7cbd5df4e710.png">

**Comment by majjoha** [comment]
Thank you for replying so quickly, @mhartington.

Last night, I was able to reach a result similar to the one in the image you posted with vim-plug. However, I am wondering why the background is closer to black than the bluish in my terminal.

<img width="1322" alt="screen shot 2016-01-14 at 07 43 13" src="https://cloud.githubusercontent.com/assets/233988/12317550/7c63b13a-ba92-11e5-86b6-257e1dd49aa1.png">

I am not sure if this causes the Neovim colorscheme to be slightly off. Anyway, thank you once again.
