### ISSUE TITLE
Light mode 

### ISSUE THREAD

**Issue by mhartington** [mhartington/oceanic-next#14]
I've wanted a light mode for a while (for day/night time editing) 

I opened an issue here https://github.com/voronianski/oceanic-next-color-scheme/issues/18

It could be as simple as swapping out some colors in an if statement. 

This would also extend to the included airline theme. 

If anyone would like to help with this, would love to get some ideas/code going. 
Would consider adding folks as co-maintainers of this repo as well.

**Comment by diffractometer** [comment]
+1 It's a great theme, one of the best. I would love a light theme but I'm too lazy to make it myself, just sayin'!

**Comment by mhartington** [comment]
Calling this one done for now.

![screen shot 2016-11-21 at 11 47 43 am](https://cloud.githubusercontent.com/assets/2835826/20491758/63eb82a6-afe0-11e6-99c8-fdf56942d0d9.png)
