### ISSUE TITLE
this color scheme has some issue with number col

### ISSUE THREAD

**Issue by wsdjeg** [mhartington/oceanic-next#15]
![2016-01-30 21 02 43](https://cloud.githubusercontent.com/assets/13142418/12695841/e7eae964-c794-11e5-936c-ac4e69c3d3ff.png)
![2016-01-30 21 03 07](https://cloud.githubusercontent.com/assets/13142418/12695842/e82a031a-c794-11e5-941c-93c344d252b6.png)

**Comment by mhartington** [comment]
what is that second theme. This is been on my todo list, and would love to get this taken care of.

**Comment by mhartington** [comment]
Should be fixed now

**Comment by wsdjeg** [comment]
sorry for the later reply,second is gruvbox, and still same as before in neovim
