### ISSUE TITLE
Background color is wrong 

### ISSUE THREAD

**Issue by olalonde** [mhartington/oceanic-next#16]
<img width="884" alt="screenshot 2016-03-07 13 07 17" src="https://cloud.githubusercontent.com/assets/416585/13583353/ac0229b0-e465-11e5-8954-3d375f33ef48.png">

Thanks for this. Everything seems fine except for the background. I assume this is because of my terminal's color scheme (iTerm2)? If so, which iTerm2 color scheme works best with oceanic-next?

**Comment by mhartington** [comment]
https://github.com/mhartington/oceanic-next-iterm

**Comment by olalonde** [comment]
Thanks, looking better now:

<img width="775" alt="screenshot 2016-03-07 13 32 25" src="https://cloud.githubusercontent.com/assets/416585/13583977/20bf9dc0-e469-11e5-8f38-f69ae42abf0c.png">

Any idea why the line number column background color is a light grey?

**Comment by mhartington** [comment]
This is how I've designed them. 

I use 

``` viml
  set relativenumber number
```

And that should give you an highlight active number.

**Comment by olalonde** [comment]
Thanks but what I meant is the grey color in ![https://raw.githubusercontent.com/mhartington/oceanic-next/master/oceanic-next-dark.nvim.png](https://raw.githubusercontent.com/mhartington/oceanic-next/master/oceanic-next-dark.nvim.png) looks more purple/dark than mine which is light grey. Is that because I'm using vim vs neovim?

**Comment by mhartington** [comment]
Ahh yes, that's in nvim. Neovim has true color support, so it can handle the raw hex values.
Vim sadly only has 256, so the grays look a little off and end up being based on what the terminal theme is.

![](https://raw.githubusercontent.com/mhartington/oceanic-next/master/oceanic-next-dark.vim.png)

**Comment by olalonde** [comment]
Ah, gotcha. Guess I should give a try to neovim then.

**Comment by olalonde** [comment]
My vim colours are different than your vim screenshot though. The colors seem a lot lighter.

**Comment by olalonde** [comment]
using yajs.vim

<img width="478" alt="screenshot 2016-03-07 14 23 04" src="https://cloud.githubusercontent.com/assets/416585/13585343/272f9adc-e470-11e5-9f00-be8afc131097.png">

**Comment by olalonde** [comment]
Oops, there was a conflict between yajs and another vim js plugin.

<img width="476" alt="screenshot 2016-03-07 14 26 01" src="https://cloud.githubusercontent.com/assets/416585/13585410/96bf3a9c-e470-11e5-8336-f8466da8f2ed.png">

Looks more like it except mine has slightly more contrast.

**Comment by mhartington** [comment]
K could, you pull down the latest Iterm color scheme again. In the iterm3 version I had to darken the color, a bit, and change the vim theme to match. Just fixed it and that should get things closer. Sorry for all the trouble right way!

**Comment by olalonde** [comment]
No worries, thanks for helping. I just downloaded iTerm 3 actually and was still getting a darker background. Anyways, it's close enough for now I think :) PS: could you put that sound cloud audio test file somewhere so I can use it to compare?
