### ISSUE TITLE
Incorrect bg color and NVIM_TUI_ENABLE_TRUE_COLOR=1 disables true colors

### ISSUE THREAD

**Issue by itsjef** [mhartington/oceanic-next#17]
Here is how the colorscheme looks like in my Terminal emulator (xfce4-terminal 0.6.3).

with **NVIM_TUI_ENABLE_TRUE_COLOR=1**
![with NVIM_TUI_ENABLE_TRUE_COLOR=1](http://imgur.com/GRFFASRl.png)

without **NVIM_TUI_ENABLE_TRUE_COLOR=1**
![without NVIM_TUI_ENABLE_TRUE_COLOR=1](http://imgur.com/8Pvmmyjl.png)
the background color is black 

How can I get it to display exactly like in your screenshots? Thanks!

**Comment by mhartington** [comment]
Could you run this and paste the screenshot? 

```
curl -s https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh | bash
```

I'm guess that xfce4 does not support true colors?

**Comment by itsjef** [comment]
Output:
![](http://imgur.com/nOgKNgFl.png)

And yes, I did some searching and [here](https://gist.github.com/XVilka/8346728) they said xfce4-terminal does not support true colors :frowning: 

Update:
Screenshot on my gnome-terminal. Looks awesome.
![](http://imgur.com/lF3AX3cl.png)

In conclusion, it's a terminal color problem, not colorscheme's. Thanks for your time! :hand:

**Comment by mhartington** [comment]
Happy to help :grin:
