### ISSUE TITLE
Background lighter on neovim

### ISSUE THREAD

**Issue by kassio** [mhartington/oceanic-next#19]
I'm using the [iterm2 Oceanic-Dark](https://github.com/mhartington/oceanic-next-iterm), and I'm having very different background color on vim and neovim:

neovim:
![nvim](https://cloud.githubusercontent.com/assets/120483/14683877/76638a90-0703-11e6-8b83-3ae3ad9b6e00.png)

vim:
![vim](https://cloud.githubusercontent.com/assets/120483/14683865/64521b82-0703-11e6-85bd-39c147f16be2.png)

**Comment by mhartington** [comment]
Whats you're terminal's type being reported as? 
Also, is this a recent update?
I have updated the neovim GUI color, but have not had a chance to update the iTerm profile yet... (shame on me)

**Comment by kassio** [comment]
On vim: `echo &term` => `xterm-256color`.
Yes, this is a recent update:

```
commit ff5285814a9bbc90e35e6c25396e6a1c2ded92bd
Author: Bram Kok <bram@bramkok.com>
Date:   Sat Apr 16 12:51:35 2016 +0200

    Update color to use original theme.
    Closes #18
```

**Comment by mhartington** [comment]
I just updated the iTerm theme, could you give that a shot?

**Comment by kassio** [comment]
The contrast on vim now is even higher:
vim:
![vim](https://cloud.githubusercontent.com/assets/120483/14691227/75c6ce8a-0726-11e6-9467-de3ddbf07ed9.png)

neovim:
![nvim](https://cloud.githubusercontent.com/assets/120483/14691233/8045db9e-0726-11e6-9ece-8f293ecb9403.png)

**Comment by eelkeh** [comment]
@kassio upgrading to the latest HEAD of neovim solved it for me!

**Comment by kassio** [comment]
Actually, I started to use the base16 colors with the ocean theme, and worked very well for me. I'll belive in @eelkeh and close this one. Thank you!
