### ISSUE TITLE
Bad contrast on matching brackets

### ISSUE THREAD

**Issue by rumpelsepp** [mhartington/oceanic-next#20]
When the cursor is placed on a bracket, it is very confusing since one cannot distinguish between the actual position of the cursor and the highlighted matched bracket.

**Comment by mhartington** [comment]
Could you post a screenshot?

**Comment by rumpelsepp** [comment]
Do you know how I can generate a gif of that? I failed with creating a screenshot since the cursor is blinking...

**Comment by mhartington** [comment]
https://gist.github.com/dergachev/4627207

**Comment by rumpelsepp** [comment]
thx.

![out](https://cloud.githubusercontent.com/assets/1961699/15197720/45eaa480-17d3-11e6-97b9-b5dfbcd01de9.gif)

gruvbox handles this better. The cursor does not disappear when you move it over the bracket. I had serious headaches today at work when programming C because of the disappearing cursor...

![out](https://cloud.githubusercontent.com/assets/1961699/15197745/74f815be-17d3-11e6-8bed-338e5a24a703.gif)

**Comment by mhartington** [comment]
Cool, thanks for gifs. I'll take a look and fix it.

**Comment by mhartington** [comment]
Hmm, could you try a minimal vimrc/init.vim for this. I wasn't able to replicate this loading only oceanic-next.

It might be a conflict from the plugin. Any chance you have something like rainbow parentheses installed?

**Comment by beeender** [comment]
I have the same problem.

```
"call <sid>hi("MatchParen",    s:gui00, s:gui03, s:cterm00, s:cterm03,  "")
call <sid>hi("MatchParen",    s:gui05, s:gui03, s:cterm05, s:cterm03,  "")
```

Above makes it much better

**Comment by mhartington** [comment]
Should be fixed now 😁
