### ISSUE TITLE
Add support for ExtraWhitespace

### ISSUE THREAD

**Issue by bananatranada** [mhartington/oceanic-next#22]
Since `ExtraWhitespace` is fairly common to [highlight unwanted spaces](http://vim.wikia.com/wiki/Highlight_unwanted_spaces), I thought it would be a nice to add it.

Only thing is that it's user-specific, so I can understand if you don't plan to support it.

Thoughts?

**Comment by mhartington** [comment]
Do you have an example of this? 
I've never used it before to be honest, but it could be a configurable option?

**Comment by bananatranada** [comment]
https://github.com/junegunn/seoul256.vim/blob/master/colors/seoul256.vim#L313

As a vim noob, I used his vimrc as a starting point and I realized he defined his variable in his own color scheme.

But I'm closing this since I configured my vimrc to remove trailing whitespaces on save. Thanks for your work!
