### ISSUE TITLE
Add support for Markdown bold & italic text

### ISSUE THREAD

**Issue by jimzenn** [mhartington/oceanic-next#23]
Markdown bold and italic text should be stylized.

**Comment by mhartington** [comment]
Testing a few new things, had to do some work to get italics working in iterm/tmux/neovim

http://bruinsslot.jp/2016/05/29/how-to-enable-true-color-for-neovim-tmux-and-gnome-terminal/

But the end result is pretty good. Would love to get your thoughts on it.

<img width="367" alt="screen shot 2016-07-17 at 7 08 27 pm" src="https://cloud.githubusercontent.com/assets/2835826/16903657/1ed4154e-4c52-11e6-84d9-15b15bdecbc6.png">

**Comment by mhartington** [comment]
Added!

**Comment by Jim-Zenn** [comment]
What terminal are you using? I did this http://bruinsslot.jp/2016/05/29/how-to-enable-true-color-for-neovim-tmux-and-gnome-terminal/ but it still doesn't show italic and bold.

**Comment by Jim-Zenn** [comment]
I'm using iTerm2

**Comment by mhartington** [comment]
Got the emails that you were having trouble, just in case you still are here what I did.

vim xterm-256color-italic.terminfo

``` shell
# A xterm-256color based TERMINFO that adds the escape sequences for italic.
#
# Install:
#
#   tic xterm-256color-italic.terminfo
#
# Usage:
#
#   export TERM=xterm-256color-italic
#
xterm-256color-italic|xterm with 256 colors and italic,
    sitm=\E[3m, ritm=\E[23m,
    use=xterm-256color,
```

``` bash
tic xterm-256color-italic.terminfo
```

Then it worked.

**Comment by jimzenn** [comment]
Yeah, I deleted the thing because I found out it’s my problem. Still, thank
you for the effort!
