### ISSUE TITLE
Extra left arrow in the airline

### ISSUE THREAD

**Issue by jimzenn** [mhartington/oceanic-next#28]
<img width="260" alt="screen shot 2016-09-20 at 22 09 04" src="https://cloud.githubusercontent.com/assets/7279131/18698407/eb90e594-7f7e-11e6-8210-1b9605124253.png">
<img width="210" alt="screen shot 2016-09-20 at 22 09 09" src="https://cloud.githubusercontent.com/assets/7279131/18698408/ed7e1854-7f7e-11e6-9d45-d28ba937c51c.png">
Is that extra left arrow supposed to be there?

**Comment by mhartington** [comment]
I know the extra orange icon on the bottom is from airline. You can fix with this in your rc file

``` viml
let g:airline_skip_empty_sections = 1
```

Not sure on the arrows on the left though. In fact, I do not have them in my setup. Maybe you have an older version of vim-airline? That seems like it would be the main cause. OceanicNext wouldn't really cause those extra icons to appear.

**Comment by jimzenn** [comment]
Thank you! That fix the airline, but tabline extension still has that extra arrow.
<img width="91" alt="screen shot 2016-09-22 at 14 43 10" src="https://cloud.githubusercontent.com/assets/7279131/18767254/eb1f5208-80d2-11e6-886c-a3f192b67247.png">
Another minor thing, I think the arrow has a different color from the bar.

**Comment by jimzenn** [comment]
Should I report this thing to some other repo? 😄

**Comment by mhartington** [comment]
Hmm, not sure I'm following, what do you mean "extra arrow"?
![screen shot 2016-09-22 at 5 48 42 pm](https://cloud.githubusercontent.com/assets/2835826/18767390/dba9eb66-80ec-11e6-901f-6ea7d07b2c65.png)

What does your full screen look like? From that screen shot, I have no idea where to look

**Comment by jimzenn** [comment]
![screen shot 2016-09-28 at 17 16 02](https://cloud.githubusercontent.com/assets/7279131/18936818/88372cde-859f-11e6-80f2-40b584642e29.jpg)

Thank you!

**Comment by mhartington** [comment]
Hmm, not sure whats up
Not able to replicate this on my end. 

Can you supply a minimal vim config?

**Comment by jimzenn** [comment]
Never mind, this is a small thing I don't want to waste your time on it. I guess I'll try to fix this later. Thank you for your attention!
