### ISSUE TITLE
JSX & XML

### ISSUE THREAD

**Issue by charliewilco** [mhartington/oceanic-next#29]
I'm getting inconsistent tags in JSX and XML. the vim-jsx plugin people suggest it's an issue with the way tags are handled in the syntax highlighting, any ideas on how to fix this?

<img width="206" alt="screenshot 2016-09-21 03 04 46" src="https://cloud.githubusercontent.com/assets/4588060/18706787/355b2526-7fa8-11e6-8392-8850afbccd17.png">
<img width="347" alt="screenshot 2016-09-21 03 04 25" src="https://cloud.githubusercontent.com/assets/4588060/18706786/35580256-7fa8-11e6-8d70-b45a584ba761.png">

**Comment by mhartington** [comment]
Are you using `pangloss/vim-javascript` and `mxw/vim-jsx`? 
I'm not a JSX expert, would you be able to provide a snippet that has the issues for me to test out?

**Comment by mhartington** [comment]
just pushed fix for this, could you pull the latest down and take a look?

**Comment by charliewilco** [comment]
OMG thanks! this worked perfect!

**Comment by charliewilco** [comment]
<img width="317" alt="screenshot 2016-09-23 08 25 40" src="https://cloud.githubusercontent.com/assets/4588060/18791395/6489a190-8167-11e6-8c77-99e590908331.png">
