### ISSUE TITLE
Airline theme issue

### ISSUE THREAD

**Issue by cjnucette** [mhartington/oceanic-next#34]
Since the last update (today) I'm getting the following message:
Could not resolve airline theme "oceanicnext". Themes have been migrated to github.com/vim-airline/vim-airline-theme

It is set in .vimrc (let g:airline_theme="oceanicnext), but if i load it manually it works.

**Comment by mhartington** [comment]
Using this minimal vimrc, Im not able to replicate

``` viml
 set runtimepath+=~/.config-test/nvim/repos/github.com/Shougo/dein.vim/
 call dein#begin(expand('~/.config-test/nvim'))
 call dein#add('Shougo/dein.vim')
 call dein#add('haya14busa/dein-command.vim')
 call dein#add('Shougo/dein.vim')
 call dein#add('mhartington/oceanic-next')
 call dein#add('vim-airline/vim-airline')
   if dein#check_install()
      call dein#install()
      let pluginsExist=1
   endif
   call dein#end()
   filetype plugin indent on
 if (has("termguicolors"))
   set termguicolors
 endif
 syntax enable
 colorscheme OceanicNext
 let g:airline_theme="oceanicnext"
 let g:airline_powerline_fonts = 1
```

Please post a minimal vimrc that has the error

**Comment by cjnucette** [comment]
Ok , I found out that there is a problem with ctrlp plugin, but it seems to be affecting  only this plugin.

**Comment by mhartington** [comment]
Are you using the active fork or the original ctrlp?

**Comment by cjnucette** [comment]
I'm using `ctrlpvim/ctrlp.vim`

**Comment by johnthepink** [comment]
I can confirm it has something to do with `ctrlp`. Going to invesitgate

**Comment by johnthepink** [comment]
I was unable to reproduce consistently. I reverted to https://github.com/mhartington/oceanic-next/commit/b938fbcfdf6d66ffc9b9eb945de8b3629c634f65 and everything is working as normal.

While trying to reproduce, for whatever reason, removing ctrlp fixed the issue for me. Adding it back in, and then removing the ctrlp styles from this theme did not fix the issue for me.

**Comment by nexusstar** [comment]
I've got the same issue, every time I start Neovim it shows the message:
`"Could not resolve ..."`. And If I enter `AirlineTheme: oceanicnext` the theme shows up. Here is my configuration and how it looks: 

![peek 2016-11-13 00-36](https://cloud.githubusercontent.com/assets/1746003/20242529/b1687bd6-a939-11e6-8c14-9fbf221222cb.gif)

And I too can confirm that removing CtrlP from my configuration just resolved it

![peek 2016-11-13 01-00](https://cloud.githubusercontent.com/assets/1746003/20242605/101e9c02-a93d-11e6-8f38-6b741ff54027.gif)

**Comment by mhartington** [comment]
can you pull and try now?

**Comment by nexusstar** [comment]
Now all works, and it's beautiful
