### ISSUE TITLE
little to no syntax highlighting on html files

### ISSUE THREAD

**Issue by kaylaharris24** [mhartington/oceanic-next#36]
Hey - I love your theme but I'm having a little trouble and was hoping you could help. Would you mind sharing a pic of a html file using your theme? I can't seem to get syntax highlighting working for html and jsx files. 

I have `Plug 'othree/html5-syntax.vim', `Plug 'pangloss/vim-javascript', { 'for': 'javascript' }`, and `Plug 'mxw/vim-jsx', { 'for': 'jsx' }` setup properly but my files look like this:

<img width="1432" alt="screen shot 2016-11-20 at 3 14 42 pm" src="https://cloud.githubusercontent.com/assets/12119723/20488302/868505a0-afd4-11e6-9f32-4a50f9f1b165.png">

here is my setup:
<img width="511" alt="screen shot 2016-11-20 at 3 15 19 pm" src="https://cloud.githubusercontent.com/assets/12119723/20488345/a34bde16-afd4-11e6-99c3-4f24a7dc45b1.png">
<img width="1399" alt="screen shot 2016-11-20 at 3 15 56 pm" src="https://cloud.githubusercontent.com/assets/12119723/20488344/a34bb0bc-afd4-11e6-9743-bfcfeb9ecd15.png">

was hoping it would look something like this:
![screen shot 2016-11-21 at 10 26 09 am](https://cloud.githubusercontent.com/assets/12119723/20488452/0406e89a-afd5-11e6-9c19-e3355ea71dae.png)

**Comment by mhartington** [comment]
This was a change I made to make things a bit clearer.

![screen shot 2016-11-21 at 11 41 43 am](https://cloud.githubusercontent.com/assets/2835826/20491482/8c4e9f04-afdf-11e6-8345-ac301f7367c3.png)


HTML elements are now a lighter color since they're typically not the most important part of the code 

Similar idea as to here.

https://github.com/cameronbourke/yoceanic-next-syntax#design-consistency

**Comment by kaylaharris24** [comment]
@mhartington  got it, thanks!

**Comment by beojan** [comment]
@kaylacohn By the way, it looks like you're using an unpatched Fira Mono, which is why your powerline doesn't have the correct symbols. Consider using [Fira Code](https://github.com/tonsky/FiraCode) instead.
