### ISSUE TITLE
Cannot disable italics for comments

### ISSUE THREAD

**Issue by sittim** [mhartington/oceanic-next#38]
In NeoVim and VIM8, Using configuration below, comments and bold is still in italics, why would it not disable it?

![selection_013](https://cloud.githubusercontent.com/assets/8825037/20676997/b063472a-b55f-11e6-8b87-ba0fd3ec0aec.png)

**Comment by mhartington** [comment]
Still need to rework this part. Toggling them got removed when I moved to estilo. Will disable them for now, and then add them back when I can configure them properly

**Comment by mhartington** [comment]
Disabled via https://github.com/mhartington/oceanic-next/commit/b1a04e8f635ad93037d313cda22c549c7b7b89bf
