### ISSUE TITLE
Incorrect Syntax highlighting

### ISSUE THREAD

**Issue by tomgatzgates** [mhartington/oceanic-next#39]
This is most likely not a problem Oceanic but I thought it might be a good place to start. 
I'm getting very different results using Oceanic in Sublime than I do with my Vim set up. 
Any ideas why this might be? I've added my minimal `.vimrc` as well. 

```
"Vundle
Plugin 'mhartington/oceanic-next'
"Plugin 'pangloss/vim-javascript'
Plugin 'othree/yajs.vim' "Seems to work better with yajs
Plugin 'mxw/vim-jsx'
"

syntax enable
" for vim 7
set t_Co=256

" for vim 8
if (has("termguicolors"))
 set termguicolors
endif

colorscheme OceanicNext
```

## Sublime
<img width="864" alt="screen shot 2016-12-04 at 08 34 04" src="https://cloud.githubusercontent.com/assets/7048758/20864958/ccdaca62-b9fc-11e6-97ef-8fcd5b3d6a4c.png">

## Vim
<img width="777" alt="screen shot 2016-12-04 at 08 33 49" src="https://cloud.githubusercontent.com/assets/7048758/20864952/b1b9701c-b9fc-11e6-8a31-a1a99bcd0c8d.png">

**Comment by anthonybrown** [comment]
I'm having the same issues in my HTML files

<img width="861" alt="screenshot 2016-12-04 07 44 52" src="https://cloud.githubusercontent.com/assets/1719818/20866218/cfcf8c32-b9f5-11e6-90f9-ef1a8e5fe097.png">

**Comment by tomgatzgates** [comment]
Seems like the `tag name` isn't being picked up correctly. I'm not sure if its the color scheme or the syntax highlighter

**Comment by mhartington** [comment]
https://github.com/mhartington/oceanic-next/issues/36

This is done on purpose.

https://github.com/cameronbourke/yoceanic-next-syntax#white-space

I like this idea of only highlighting the relevant bits, and everything else can just fade to the background.

**Comment by anthonybrown** [comment]
The tags in the HTML used to be read now they're white, can I change it back?

**Comment by mhartington** [comment]
If you want, you can add them back with 

```
hi htmlTagName guifg=#c0c5ce ctermfg=251
hi htmlEndTag guifg=#c0c5ce ctermfg=251
```

But I do not want to revert this change. It's much easier to read this way.

**Comment by anthonybrown** [comment]
Actually, looking at the comparison, I like it. I thought the theme broke because on my other machine, they're still red.
👍

**Comment by tomgatzgates** [comment]
Thanks @mhartington, I was unaware this was a deliberate change. Good to know 👍

**Comment by anthonybrown** [comment]
@mhartington  can I use the commit before you changed the theme to use white instead of the red?
how would I do that?

**Comment by mhartington** [comment]
See this comment.

https://github.com/mhartington/oceanic-next/issues/39#issuecomment-264722112

Add those two lines to your vimrc

**Comment by anthonybrown** [comment]
Those colors are white @mhartington 
and I have to say, this is the best theme I've used for JavaScript and React, love it.

**Comment by PezCoder** [comment]
@mhartington The logic behind this is quite right but in case of jsx. It's looking like this:
![image](https://cloud.githubusercontent.com/assets/8057916/21073292/227a048a-bf00-11e6-9c84-44ac86d7e42a.png)

i.e the closing tag doesn't have that angular brackets colored which kind of mixes up in the text & It's hard to detect where the closing tag is.

Either it should be colored or should have different color than white (like in xml for other color schemes) don't you think ?

**Comment by mhartington** [comment]
@PezCoder open a new issue.

**Comment by anthonybrown** [comment]
I miss how when one of my div tags was blue  the closing one would be red, that way I could easily scan my files. Now, it's not so easy with the white. I have to agree with @PezCoder 

![screen shot 2016-12-12 at 1 27 43 pm](https://cloud.githubusercontent.com/assets/1719818/21111363/3266eaa0-c06f-11e6-8a62-e888aa351d7f.png)

**Comment by mhartington** [comment]
You can fork and make your own changes. 
This is how I would like the theme to work, as it makes things easier to read, and points out the important parts.

![screen shot 2016-12-12 at 1 58 03 pm](https://cloud.githubusercontent.com/assets/2835826/21112255/1d795f34-c073-11e6-9cde-9a879e523f9b.png)

**Comment by anthonybrown** [comment]
Totally understand. :)
