### ISSUE TITLE
Background color different when in tmux

### ISSUE THREAD

**Issue by olalonde** [mhartington/oceanic-next#40]
I just recently updated oceanic-next and setup truecolor support in tmux. For some reason, the background in Vim is slightly different when I open vim inside a local tmux session.

Vim launched from inside tmux session:

<img width="542" alt="screenshot 2016-12-13 18 20 35" src="https://cloud.githubusercontent.com/assets/416585/21167379/fc5678d4-c160-11e6-8824-906290b9372e.png">

Vim launched directly from iTerm2:

<img width="576" alt="screenshot 2016-12-13 18 22 58" src="https://cloud.githubusercontent.com/assets/416585/21167421/31b5603a-c161-11e6-989b-95ff261d3a29.png">

```
~$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 11 2016 14:44:53)
MacOS X (unix) version
Included patches: 1-27
Compiled by Homebrew
...
~$ tmux -V
tmux 2.3
```

iTerm2 3.0.12. I also made sure I had the most recent version of oceanic next iTerm colors.

I have this in my ~/.tmux.conf:

```
# enable truecolor support
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
```

**Comment by shelldandy** [comment]
make sure to also pass the colors to your iterm, also remove all of your tmux packages and re-install them again that worked for me

Here are my dotfiles maybe they can help you since i was there and solved it but can't really remember what did the trick

https://github.com/mike3run/dotfiles

**Comment by mhartington** [comment]
how can I replicate? minimal vimrc? I need more info

**Comment by shelldandy** [comment]
@mhartington i had this issue as well it has nothing to do with the color scheme its mainly a tmux config situation

**Comment by shelldandy** [comment]
im like 90% sure this gets solved by uninstalling and reinstalling both tmux plugins and vims plugins i think thats what solved it for me at least

**Comment by olalonde** [comment]
Thanks. Aren't you using neovim though?

**Comment by olalonde** [comment]
I just tried again with very minimal tmux/vim configuration but same result:

```
~$ cat .vimrc
" Load Vundle + plugins
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

syntax enable

if (has("termguicolors"))
 set termguicolors
endif

colorscheme OceanicNext

let g:airline_theme='oceanicnext'

~$ cat .vimrc.bundles
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'mhartington/oceanic-next'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

~$ cat .tmux.conf
set -g prefix C-Space
unbind-key C-b
bind-key C-Space select-pane -t :.+

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
```

**Comment by olalonde** [comment]
I'm not sure if it's related but I noticed that if `set background=dark` messes up the theme if it's under `colorscheme OceanicNext`.

<img width="377" alt="screenshot 2016-12-13 19 52 03" src="https://cloud.githubusercontent.com/assets/416585/21169051/b5bd2e1a-c16d-11e6-9fb5-8b9496e34385.png">
<img width="387" alt="screenshot 2016-12-13 19 51 47" src="https://cloud.githubusercontent.com/assets/416585/21169050/b5bab8d8-c16d-11e6-9607-a66ef649b017.png">

**Comment by olalonde** [comment]
@mhartington do you need more info to reproduce?

**Comment by olalonde** [comment]
I did the true color test in tmux to check whether it was working properly and it seems to be ok:

In tmux:

<img width="741" alt="screenshot 2016-12-13 20 02 30" src="https://cloud.githubusercontent.com/assets/416585/21169211/2062780a-c16f-11e6-8eb6-67494c4f4d39.png">

Outside tmux:

<img width="752" alt="screenshot 2016-12-13 20 03 36" src="https://cloud.githubusercontent.com/assets/416585/21169229/44c1e154-c16f-11e6-8d4f-fd8f682f52ac.png">

```bash
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s s s s s s s s s s s s s s s s;
    for (colnum = 0; colnum<256; colnum++) {
        r = 255-(colnum*255/255);
        g = (colnum*510/255);
        b = (colnum*255/255);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

**Comment by olalonde** [comment]
This seems related though [the fix](http://unix.stackexchange.com/questions/197391/background-color-mismatch-in-vim-and-tmux) doesn't work for me (`export TERM=screen-256color` just disables all coloring).

<img width="444" alt="screenshot 2016-12-13 20 33 50" src="https://cloud.githubusercontent.com/assets/416585/21169710/88a4444e-c173-11e6-9263-1b86df2c93c4.png">

**Comment by olalonde** [comment]
Don't ask me why (suggested by someone on IRC) but adding this to my `.vimrc` fixed the issue!

```viml
set t_ut=
```

edit: seems related to https://github.com/vim/vim/issues/804
edit: and answer on Stackoverflow: http://stackoverflow.com/a/15095377/96855

**Comment by dylan-chong** [comment]
Tip: I wasn't able to get my setup working with the advice in this thread until i restarted tmux with `tmux kill-server`.

**Comment by gontcharovd** [comment]
I had this problem the other day. In my case removing the line `let g:oceanic_next_terminal_italic = 1` from my .vimrc file resolved it.

My .vimrc: https://github.com/gontcharovd/vim/blob/master/vimrc
