### ISSUE TITLE
Markdown Links don't show

### ISSUE THREAD

**Issue by shelldandy** [mhartington/oceanic-next#41]
I just recently found out that on a `.md` file the links will be rendered with an underline (which is fine) but also the insides of the parens get the same color as the background

![captura de pantalla 2016-12-13 a la s 21 07 03](https://cloud.githubusercontent.com/assets/7088511/21168318/b3f1ceaa-c178-11e6-9e30-6f1c912f0241.png)

If i delete the parens the text appears again so i think its a really minor thing going on here.

![captura de pantalla 2016-12-13 a la s 21 11 35](https://cloud.githubusercontent.com/assets/7088511/21168338/d2fd92fc-c178-11e6-8eda-ca05a757750e.png)

Thanks for all the hard work into this awesome color scheme! 😄

**Comment by mhartington** [comment]
Sounds like the markdown syntax file issue.
What markdown syntax plugin are you using?

**Comment by shelldandy** [comment]
I am not using any specific markdown plugin or syntax

However I am using vim-polyglot

https://github.com/sheerun/vim-polyglot

That would be the only syntax plugin I'm using besides the ones that are recommended to work with the theme

So maybe it has something to do with it?

**Comment by mhartington** [comment]
Read the syntax that it's providing docs

https://github.com/plasticboy/vim-markdown#syntax-concealing
