### ISSUE TITLE
JSX Angle brackets are colorless

### ISSUE THREAD

**Issue by PezCoder** [mhartington/oceanic-next#42]
JSX closing angle brackets are colored as white which mixes up with the text & it's hard to detect where a tag ends.
![image](https://cloud.githubusercontent.com/assets/8057916/21073292/227a048a-bf00-11e6-9c84-44ac86d7e42a.png)

That green color for angle brackets would really be helpful. 

I'm using:
VIM 7.4.52
iTerm2

**Comment by PezCoder** [comment]
@mhartington can I create a pr for this ? I didn't find a contributing guideline though. 
It would be great if you can guide me in right direction.

**Comment by mhartington** [comment]
Testing the latest in neovim.

![screen shot 2016-12-15 at 12 17 47 pm](https://cloud.githubusercontent.com/assets/2835826/21234409/8c263eda-c2c0-11e6-9271-21dac9f9cbe4.png)

**Comment by PezCoder** [comment]
@mhartington hmm my bad, I did a latest update & it's perfect. 😄 Closing this,  thanks.
