### ISSUE TITLE
colors difference when matching with Atom

### ISSUE THREAD

**Issue by fpereira1** [mhartington/oceanic-next#44]
Hey, huge thanks for this plugin, it is stunning.
I have the same or a similar issue to mentioned in #5. 

The problem I am having is in macvim/terminal/iTerm.

Here's how it looks on macvim:
![image](https://cloud.githubusercontent.com/assets/868423/21845862/4562cc9e-d859-11e6-8084-32a3f044c8a9.png)

Which is a bit different to how it's displayed in the README.md
![image](https://raw.githubusercontent.com/mhartington/oceanic-next/master/oceanic-next-dark.vim.png)

I have the recommended plugins installed and I am using macvim/vim 8.  Am I missing something?

Thanks!

**Comment by mhartington** [comment]
Do you have a minimal vimrc to test against? I need one to test.

**Comment by fpereira1** [comment]
hey, thanks for the reply.  Here's a simplified version of my vimrc.

The issue looks more apparent in another file, if it helps.

macvim: 
![image](https://cloud.githubusercontent.com/assets/868423/21864040/d14d5350-d8a4-11e6-9918-ad73c0651092.png)

Atom:
![image](https://cloud.githubusercontent.com/assets/868423/21864062/ec5f1930-d8a4-11e6-8221-ae513cebcb4f.png)


*Minimal vimrc to test*

```
" Necessary for lots of cool vim things
set nocompatible

" set nowrap by default
set nowrap

syntax enable
set t_Co=256
set background=dark

filetype plugin indent on

set encoding=utf-8

" for vim 8
if (has("termguicolors"))
 set termguicolors
endif

" font size
if has("gui_running")
  set mouse=
  set linespace=6
  set guifont=Menlo\ for\ Powerline:h18
  set guioptions="egmtT"
endif

" Vundle setup
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tomtom/tcomment_vim'
Plugin 'sheerun/vim-polyglot'
"Plugin 'leafgarland/typescript-vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'mhartington/oceanic-next'
Plugin 'othree/yajs.vim'
Plugin 'othree/html5.vim'
Plugin 'HerringtonDarkholme/yats.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-syntastic/syntastic'

" All of your Plugins must be added before the following line
call vundle#end()            " required

" color scheme
colorscheme OceanicNext
```

**Comment by mhartington** [comment]
mind sending a snippet of the code so I can add to the test files? 


Quickly looking, you have these 3 syntax files

```
Plugin 'sheerun/vim-polyglot'
Plugin 'othree/yajs.vim'
Plugin 'pangloss/vim-javascript'
```
Which could be causing conflicts. Mind just using `yajs.vim` and tests?

Also note: Between vim/nvim and atom/sublime, it may not always be a 1:1 match

**Comment by fpereira1** [comment]
Thanks @mhartington. The file in my example is: https://github.com/cheeriojs/cheerio/blob/master/lib/cheerio.js#L1-L42

I have disabled all other plugins:
![image](https://cloud.githubusercontent.com/assets/868423/21876589/021b0312-d8e9-11e6-90f0-a96bc4cc83cb.png)

![image](https://cloud.githubusercontent.com/assets/868423/21876557/c8a336c2-d8e8-11e6-8a7b-3beed72c9f48.png)

**Comment by mhartington** [comment]
Hmm, alright, I'll see what I can do

**Comment by fpereira1** [comment]
if it's a missing feature, that's all good, I was just wondering if I was missing something. I've started looking at how this is done, so I might be able to submit a PR

**Comment by mhartington** [comment]
Hey sorry, I've been busy with work. If you'd like to give it a shot and make a PR, that would be great! 

I generate this theme using estilo so

```
npm i -g estilo
```

Then make any changes you want and run `estilo render` to generate the new changes.

A nice little tool I have also is this 

```
  nnoremap <leader>e :call <SID>SynStack()<CR>
  function! <SID>SynStack()
    if !exists("*synstack")
      return
    endif
    echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
  endfunc
```

This will echo the syntax groups. Useful for debugging

**Comment by fpereira1** [comment]
Awesome, thanks!
I have started by filling in the values in this file: https://github.com/mhartington/oceanic-next/blob/master/estilo/syntax/yajs.yml

My changes so far are: https://github.com/mhartington/oceanic-next/compare/master...fpereira1:javascript_atom_match?expand=1
However, from now I will change the `yajs.yml` file instead of `javascript.yml`

**Comment by landabaso** [comment]
I'm having exactly the same issue.
@fpereira1 did you find out how to solve it?

**Comment by fpereira1** [comment]
@landabaso I found that some of the syntax is not implemented. Check my branch on https://github.com/mhartington/oceanic-next/compare/master...fpereira1:javascript_atom_match?expand=1

I don't know much about syntax highlighting in vim and I spent quite a bit of time looking into it.

What also worked for me was to use the typescript syntax highlighting on js files.  you can do that with the typescript plugins then run `set syntax=typescript`

My next action on this would be to port the typescript syntax into this plugin.

**Comment by ExpandingMan** [comment]
I'm having the same issue as well.  In particular, it seems operators are not being highlighted correctly.

**Comment by mhartington** [comment]
Pull requests as alway welcomed.
I'm closing this for now, as things look fine for me. But if anyone wants to make a pull request I will gladly accept it.
