### ISSUE TITLE
Italics/Bold Status

### ISSUE THREAD

**Issue by shelldandy** [mhartington/oceanic-next#45]
Hey man was wondering if there has been any progress regarding the ability to have italics for the comments.

I've seen a couple themes do it correctly for example:

https://github.com/crusoexia/vim-monokai

Maybe it helps as inspiration. I'll try to look more into it and see if I can help.

But in the meantime I feel leaving the issue open helps keep track of the situation

**Comment by mhartington** [comment]
yeah, I haven't really gotten around to it. 
Since I use estilo to generate the styles for this, I'd like to add the functionality back there first. 
Need to make a PR first, but it should be possible
