### ISSUE TITLE
Code in help text is rendered as comments

### ISSUE THREAD

**Issue by rumpelsepp** [mhartington/oceanic-next#47]
Code examples in the help pages are formatted as comments:

![screenshot from 2017-03-23 22-51-56](https://cloud.githubusercontent.com/assets/1961699/24271925/5ad9f1f2-101b-11e7-96de-0f3877a777d3.png)

A similar issue was [here](https://github.com/rakr/vim-one/issues/35). Maybe the fix there helps you in finding an appropriate fix here. :)

**Comment by mhartington** [comment]
Ahh, good catch. I'll try to fix that tonight or tomorrow morning

**Comment by mhartington** [comment]
Bit late..but should be fixed now.

**Comment by rumpelsepp** [comment]
Awesome. Thanks!
