### ISSUE TITLE
getting weird colors

### ISSUE THREAD

**Issue by majodu** [mhartington/oceanic-next#48]
#vimrc
<img width="650" alt="screen shot 2017-03-28 at 10 45 18 pm" src="https://cloud.githubusercontent.com/assets/20195279/24436217/48a8b09a-1408-11e7-85d9-b18499bf7bfa.png">

# Problems summary
getting weird colors in vim
the only plugin in the bundles folder is this one

#image of test file
<img width="648" alt="screen shot 2017-03-28 at 10 50 15 pm" src="https://cloud.githubusercontent.com/assets/20195279/24436325/ffc1413e-1408-11e7-8451-ef61d63c07d2.png">

## Environment Information
macOS sierra 10.12.3
 * terminal: iterm2 v3.0.15
 * vim/nvim version: nvim v0.1.7

**Comment by milowyner** [comment]
I'm getting those same colors, which look quite different from the screenshots of this theme and how it looks in other text editors.

**Comment by mhartington** [comment]
Please open a new issue and fill out the issue template.
