### ISSUE TITLE
Backticks and asterisks in markdown

### ISSUE THREAD

**Issue by jimzenn** [mhartington/oceanic-next#49]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
When entering backtick ` in markdown file, it will create an asterisk * before it, and as you type more backticks, it will behave very weirdly.
I disabled this plugin, and the problem is fixed. Thus I assume this plugin caused the bug.

## Expected

Enter backtick, get backtick.

## Environment Information

 * terminal: iTerm2
 * vim/nvim version: 0.2.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" General {{{

" Set to auto read when a file is changed from the outside
set autoread

" Use par for prettier line formatting
set formatprg=par
let $PARINIT = 'rTbgqR B=.,?_A_a Q=_s>|'

" }}}

" vim-plug {{{

if has('nvim')
  call plug#begin('~/.config/nvim/bundle')
else
  call plug#begin('~/.vim/bundle')
endif

" Support bundles
Plug 'ervandew/supertab'
Plug 'nathanaelkane/vim-indent-guides'

" Colorscheme
Plug 'mhartington/oceanic-next'

call plug#end()

" }}}

" User Interface {{{

" Height of the command bar
set cmdheight=1
set listchars=tab:>-,trail:·

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Colors and Fonts {{{

if (has("nvim"))
  set termguicolors
endif

" Syntax highlighting
syntax enable

" Tell Vim what the background color looks like
set background=dark

" try setting the scheme
colorscheme OceanicNext

" set the encoding if it's not neovim
if !has('nvim')
  set encoding=utf8
endif

" }}}

```

## The reproduce ways from neovim starting

 1. open any markdown file
 2. try entering backticks
 3. get weird things

## Screen shot (if possible)

![image](https://cloud.githubusercontent.com/assets/7279131/24589251/4aeca2ee-178c-11e7-83e7-2672b6a055bc.png)

**Comment by jimzenn** [comment]
If you cannot reproduce the problem, let me know. I check my configs again.

**Comment by mhartington** [comment]
Hmm, I'm not able to replicate on my end.

![](http://g.recordit.co/fYCwW2MVtl.gif)

**Comment by jimzenn** [comment]
Thank you for checking! I’ll look into my own vimrc then.

**Comment by mhartington** [comment]
Closing for now.
