### ISSUE TITLE
Really weird colors

### ISSUE THREAD

**Issue by davidmatas** [mhartington/oceanic-next#5]
Hi! I'm trying to reproduce my Oceanic Next Sublime colorscheme in vim but I have really weird colors.
<img width="644" alt="screen shot 2015-09-19 at 21 09 42" src="https://cloud.githubusercontent.com/assets/271760/9977764/0b2ea1bc-5f13-11e5-9952-05eaca919241.png">

Any clues?

**Comment by davidmatas** [comment]
I use iterm2 with `xterm-256color config` and in this is what I have in `.vimrc`:

```
syntax enable
 set t_Co=256
 colorscheme OceanicNext
 set background=dark
```

with `vim-javascript` syntax installed

**Comment by mhartington** [comment]
Hmm, alright. I'll check it out. 

Mike Hartington

**Comment by davidmatas** [comment]
I think maybe it is something related with my iterm or vim config because other colorschemes also seem weird, but don't know why :/

## 

David Matas

**Comment by mhartington** [comment]
Hmm, whats your terminal theme? Seems to be related to that.

**Comment by mhartington** [comment]
Hmm, this seems like limitation of regular vim, I didn't notice it since I use an iterm theme with oceanic next.

https://github.com/mhartington/oceanic-next-iterm

I'd suggest installing that and seeing if things works. Let me know if it doesn't

**Comment by davidmatas** [comment]
Nothings happens when I import that theme, iterm keeps showing the last theme used :/

**Comment by davidmatas** [comment]
![iterm](https://cloud.githubusercontent.com/assets/271760/9982040/e692cb14-5fce-11e5-9928-f59625148e59.gif)

**Comment by mhartington** [comment]
Hmm, try quitting iterm and try again. Not sure what's up. 

Mike Hartington

**Comment by davidmatas** [comment]
Same

**Comment by mhartington** [comment]
Alright. I'm about to get on a plane, but would be up for a google hangout later to take a look? Not sure what's going on and that would help solve it faster. 

Mike Hartington

**Comment by davidmatas** [comment]
Terminal.app shows the vim colorscheme in the same way

![screen shot 2015-09-20 at 19 55 16](https://cloud.githubusercontent.com/assets/271760/9982122/9f240510-5fd1-11e5-99e7-0378d0ed1cd6.png)

**Comment by davidmatas** [comment]
For hangout better tomorrow

**Comment by mhartington** [comment]
Sounds good. 

Want to shoot me an email so I can send you an invite? My email mikehartington at gmail dot com

Mike Hartington

**Comment by okhomenko** [comment]
So what was the solution? I have the same problem. Imported scheme into iTerm2, but when select it - colors doesn't change.

**Comment by mhartington** [comment]
I need to updat the iterm theme. Some issue with how iterm3.0 and 2.x handle things. Let me look at it this afternoon

**Comment by mhartington** [comment]
Just updated the iterm colors
https://github.com/mhartington/oceanic-next-iterm/commit/5d76836c03d5056bc6182fc4188f694167080d66
Please download the theme and let me know if it works.

**Comment by fpereira1** [comment]
Hey, huge thanks for this plugin, it is stunning.
I have the same or a similar issue to mentioned in here.  What there a resolution?

The problem I am having is in macvim/terminal/iTerm.

Here's how it looks on macvim:
![image](https://cloud.githubusercontent.com/assets/868423/21845318/0c680438-d857-11e6-8fc4-4916f0ffe178.png)

And here's on Atom:
![image](https://cloud.githubusercontent.com/assets/868423/21845345/25b01354-d857-11e6-9c70-686defd5784e.png)

I have the recommended plugins installed, and I am using macvim/vim 8.  Are you able to help debug this?

Thanks!
