### ISSUE TITLE
Color column is overriding the search highlight

### ISSUE THREAD

**Issue by kassio** [mhartington/oceanic-next#50]
# Problems summary

Color column is overriding the search highlight

## Expected

The search highlight to override the color column

## Environment Information
 * terminal: iterm2 (Build 3.0.15)
 * vim/nvim version:
```
$ nvim --version
NVIM v0.2.0-1148-gddfa0359
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170402-6837-1f53nel/build/config -I/tmp/neovim-20170402-6837-1f53nel/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170402-6837-1f53nel/build/src/nvim/auto -I/tmp/neovim-20170402-6837-1f53nel/build/include
Compiled by kborges@13592-storage

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-ddfa035/share/nvim"
```

## Provide a minimal vim rc with less than 50 lines (Required!)
```viml
set runtimepath-=~/.config/nvim
set runtimepath+=~/.config/nvim/_packs/oceanic-next
set colorcolumn=3
colorscheme OceanicNext
```

## The reproduce ways from neovim starting

 1. With `colorcolumn` and `highlightsearch` enabled;
 2. When searching a term that is in the `colorcolumn` position
 3. The `colorcolumn` is overriding the highlight search color.

## Screen shot (if possible)
On this example I searched for `end` (with the `set colorcolumn=3`):
<img width="118" alt="nvim" src="https://cloud.githubusercontent.com/assets/120483/24590890/59ab5602-17ed-11e7-89a5-d3f621e6a9b4.png">

**Comment by mhartington** [comment]
Looked at a bunch of other themes as well as vim/neovim's own built ins, this seems to be the default behaviour. 

<img width="364" alt="screen shot 2017-04-02 at 8 24 48 pm" src="https://cloud.githubusercontent.com/assets/2835826/24592338/85e2c4ea-17e2-11e7-83b5-e4db36e8a117.png">
<img width="335" alt="screen shot 2017-04-02 at 8 25 08 pm" src="https://cloud.githubusercontent.com/assets/2835826/24592339/8a859c5c-17e2-11e7-81de-2f8bd10203d4.png">
<img width="291" alt="screen shot 2017-04-02 at 8 25 19 pm" src="https://cloud.githubusercontent.com/assets/2835826/24592345/931174ae-17e2-11e7-8d0a-1097554519b4.png">


Did some googling and couldn't find others reporting the same thing so must not be something people have noticed before? Not quite sure.

**Comment by mhartington** [comment]
Asked a few others, this does appear to be the default and does not have a way to override.

**Comment by kassio** [comment]
I saw [this](https://github.com/chriskempson/base16-vim/issues/39) @mhartington, and it seems that it was solved. Isn't it possible to at least keep the foreground colour of the syntax?

**Comment by mhartington** [comment]
Doesn't appear to be "solved" to me.
Loaded the base16 themes and they have the same results.

![screen shot 2017-04-03 at 9 35 34 am](https://cloud.githubusercontent.com/assets/2835826/24611690/f49ccaca-1850-11e7-96f1-0368c9d02421.png)

**Comment by mhartington** [comment]
Comments from some others 

>Yes, ColorColumn has a higher priority than Incsearch. Since that priority is handled internally there's AFAIK no runtime-level workaround.

**Comment by kassio** [comment]
Thank you for all effort, sad that has no solution.

**Comment by kassio** [comment]
So, I was reading the `:h hi` documentation and trying to find a _solution_ for that when I found this **standout** option, which is not very well documented, but solved the problem on my setup. I wasn't able to make it work with a minimum `vimrc`, however I found out that with this minimum `vimrc` if I reload the `vimrc` (`:so %`) the highlight works, but only if the `termguicolors` is enabled:
```viml
set runtimepath-=~/.config/nvim
set runtimepath+=~/.config/nvim/_packs/oceanic-next

set termguicolors
set colorcolumn=80,2

set background=dark
colorscheme OceanicNext

hi! Search term=standout gui=standout guifg=#fac863 guibg=#65737e
```
![hls](https://cloud.githubusercontent.com/assets/120483/24649330/a149ce9e-191e-11e7-8ab9-4f6bf8ff37e6.gif)

[On my setup](https://github.com/kassio/nvimfiles), on the other hand, it works without the reloading:
![my-hls](https://cloud.githubusercontent.com/assets/120483/24649781/13a90b70-1920-11e7-8fbf-3dff632bc35f.gif)

For me the problem is ~hacked~ fixed, I'd just like to share what I found
