### ISSUE TITLE
Incorrect background color in neovim in tmux

### ISSUE THREAD

**Issue by yanneyanne** [mhartington/oceanic-next#51]
# Problems summary
When using neovim in tmux the background color renders in an incorrect brown/gray shade. The color scheme works as expected in neovim outside of tmux. 

## Environment Information

 * terminal: iTerm2 3.1
 * nvim version: 0.1.7
 * tmux version: 2.3

I am using the recommended iterm2 terminal color scheme which has been added in the iTerm preferences. I am not sure if this is a result of the theme or tmux. However, I have previously used solarized which has worked fine under the current configurations. I am also using zsh and oh-my-zsh if that matters at all.

## Minimal conf files
.vimrc:
```vim
call plug#begin('$HOME/.config/nvim/plugged')
...
Plug 'mhartington/oceanic-next'
...
call plug#end()

" For Neovim 0.1.3 and 0.1.4
let $NVIM_TUI_ENABLE_TRUE_COLOR=1

" Or if you have Neovim >= 0.1.5
if (has("termguicolors"))
 set termguicolors
endif

syntax enable
colorscheme OceanicNext
```

.tmux.conf:
```tmux
...
set -g default-terminal "screen-256color"
```

## To reproduce 

Open nvim in tmux.

## Screenshots
Outside of tmux:
<img width="485" alt="screen shot 2017-04-17 at 11 39 40" src="https://cloud.githubusercontent.com/assets/15113131/25085467/9ea54e68-2362-11e7-96dd-b73ffdf9c220.png">

Inside tmux:
<img width="488" alt="screen shot 2017-04-17 at 11 39 56" src="https://cloud.githubusercontent.com/assets/15113131/25085468/a067e706-2362-11e7-9c01-bf4a2f326d5c.png">

**Comment by yanneyanne** [comment]
This was an issue with truecolor in tmux. It was fixed with
```
tmux attach
tmux set-option -ga terminal-overrides ",xterm-256color:Tc"
tmux detach
tmux attach
```
in the terminal. Just in case anyone else encounters this!

**Comment by nonwiz0** [comment]
> This was an issue with truecolor in tmux. It was fixed with
> 
> ```
> tmux attach
> tmux set-option -ga terminal-overrides ",xterm-256color:Tc"
> tmux detach
> tmux attach
> ```
> 
> in the terminal. Just in case anyone else encounters this!



> tmux attach

It doesn't work in my case.

This is how i made it work, add this in .tmux.conf
```
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
```
