### ISSUE TITLE
Q: It is possible to change the background color?

### ISSUE THREAD

**Issue by felixsanz** [mhartington/oceanic-next#52]
My background color doesn't really match the oceanic next that i'm using on other places (like terminals), it is possible to change it? I had no luck trying to find a solution. Thanks

**Comment by mhartington** [comment]
Hi there! I'm going to close this issue as there is no information provided. If there is an issue, please open a **new** issue and provide the information we request in the issue template.

**Comment by felixsanz** [comment]
@mhartington Well, it's a question not an issue! I'm getting the expected background color, i'm just asking if it's possible to overwrite it because i'd prefer a darker one

**Comment by mhartington** [comment]
As stated in the issue template....

Please provide screen shots.

**Comment by felixsanz** [comment]
On the right is the theme. I think the background color is correct but i'd prefer the darker one from the left (i got it exporting the iterm2 oceanic-next theme and importing it into terminal.sexy -and then re-exporting for my terminal, which is `st`-)

![nvim](http://i.imgur.com/6HxIOSw.png)

**Comment by mhartington** [comment]
Im not following. Please open a new issue and provide all the information the issue template asks for. I'm not playing 50 questions.
