### ISSUE TITLE
Q: It is possible to change the background color? 

### ISSUE THREAD

**Issue by felixsanz** [mhartington/oceanic-next#53]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
No problems, just want to change the background color.

## Expected
Background color changed with my own custom value

## Environment Information

 * terminal: st
 * vim/nvim version: nvim 0.2.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
" Theme
syntax enable

if (has("termguicolors"))
set termguicolors
endif

colorscheme OceanicNext
```

## The reproduce ways from neovim starting

 1. Open `nvim`

## Screen shot (if possible)

Left, desired color.
Right, the color i'm getting
![color](https://camo.githubusercontent.com/5a05c3e88eea8d4a19e837abe4add1d1d800e732/687474703a2f2f692e696d6775722e636f6d2f364878494f53772e706e67)

**Comment by mhartington** [comment]
The screenshot on the right is the correct color. If you want something else, feel free to make your own theme.

**Comment by felixsanz** [comment]
I never said it was the wrong color. In fact, i said it is the right color. Why are you so rude man? Bad day?  Bad week? Bad year?

**Comment by mhartington** [comment]
Not being rude, just timely. You're asking to change the background color of your vim. That is possible, but it is not a question for here. Try stackoverflow

**Comment by felixsanz** [comment]
@mhartington Normally themes allow color overriding like:

```
let g:oceanicnext_color_overrides = {
\ "black": {"gui": "#2F343F", "cterm": "235", "cterm16": "0" }
\}
```

If that were the case, it would be related to your theme, not vim at all.

So yes, it's a question for here. Or even a feature request if the option doesn't exist yet. But I'll stop wasting both's time since you are so unfriendly to the community/users. Please, don't open source with this attitude. Bye.

**Comment by mhartington** [comment]
Hmmm, I dont think that would fit into what I want for oceanic-next, but thanks for the idea.

**Comment by felixsanz** [comment]
Since i really love to help others, if someone comes behind me, here is a snippet that will override colors in a theme.

```viml
function! AdjustTheme()
     hi! Normal guifg=#c0c5ce ctermfg=251 guibg=256 ctermbg=256 " <- example
endfunction

augroup ThemeOverrides
    autocmd!
    autocmd ColorScheme OceanicNext call AdjustTheme()
augroup END

colorscheme OceanicNext
```

You can get a list of those lines for Oceanic Next [here](https://github.com/mhartington/oceanic-next/blob/master/colors/OceanicNext.vim).
