### ISSUE TITLE
Indentlines color mismatch

### ISSUE THREAD

**Issue by PezCoder** [mhartington/oceanic-next#54]
# Problems summary
I want to know the process of getting those indent lines as specified in the readme screenshot.
I tried using this for indent Line
```vim
Plugin 'Yggdroot/indentLine'
```
& using this line `let g:indentLine_setColors = 0` as specified in their documentation to apply my colorscheme's color but the color of indent lines is very different for me than in your readme screenshot.

Questions:
1. What plugin did you use for indent lines ?
2. If the same plugin, can you help me fix the colors ?

## Environment Information
 * terminal: iterm2 with oceanic next theme
 * vim version: 8.0.187

## Minimal VIMRC

```vim
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'othree/yajs.vim'
Plugin 'mhartington/oceanic-next'
Plugin 'Yggdroot/indentLine'

call vundle#end()
filetype plugin indent on

if (has("termguicolors"))
    set termguicolors
endif

let g:indentLine_setColors = 0
set background=dark
colorscheme OceanicNext
set number
set ts=2
set shiftwidth=2
set softtabstop=2
set expandtab
```

## Screen shot
<img width="295" alt="screen shot 2017-06-04 at 7 04 30 pm" src="https://cloud.githubusercontent.com/assets/8057916/26762046/a87be908-4958-11e7-9c6a-7058ff91df5a.png">

Sample snippet mentioned in screenshot:
```js
function getName() {
  return function() {
    var x = 'nova';
    var y = x + 'hypernova';

    return x + y;
  };
}
```

**Comment by mhartington** [comment]
Yeah I  remember this being an issue. Let me dig back later on today and see what the solution was. I actually stopped using indent-line since neoformat clears out the marks

**Comment by PezCoder** [comment]
Actually leave it, I think this looks ugly anyways, thanks for the help though.

**Comment by mhartington** [comment]
> I think this looks ugly anyways

What the indent lines?

**Comment by sittim** [comment]
Huh? here is how it looks on my screen, to me its beautiful

![selection_110](https://user-images.githubusercontent.com/8825037/26849051-b08d9398-4ad0-11e7-9eb7-8f55f1650c16.png)

**Comment by PezCoder** [comment]
@mhartington yes the indent lines, I miss sublime's graphics sometimes. 😿

**Comment by mhartington** [comment]
<p>&macr;\_(ツ)_/&macr;</p>

you can change the indent line marker to something a bit more visually appealing
