### ISSUE TITLE
Diff UI suggestion for current line no. hightlighter

### ISSUE THREAD

**Issue by PezCoder** [mhartington/oceanic-next#55]
# Suggestion
Will you be interested in making the current line highlighted number to get highlighted in-place rather than shifting on to the left ?
Something like this: 
<img width="131" alt="screen shot 2017-07-24 at 9 52 34 am" src="https://user-images.githubusercontent.com/8057916/28508095-eaf984b0-7055-11e7-9297-116568157657.png">
(colors are from different scheme avoid those, see just the line numbers)

I would be happy to do it if you agree.

**Comment by mhartington** [comment]
Something along the lines of this? 
Line number 5
![screen shot 2017-07-24 at 9 44 42 am](https://user-images.githubusercontent.com/2835826/28526202-caf71516-7054-11e7-962f-e587412fe8d0.png)

**Comment by PezCoder** [comment]
Yo.. Looks perfect 👌🏼

**Comment by mhartington** [comment]
I added an option for this

```viml
let g:oceanic_next_highlight_current_line = 1
```

be sure to add `set cursorline` too.

**Comment by mhartington** [comment]
Having just reverted this commit, to get this effect again, add the following to your rc file.

```viml
colorscheme OceanicNext
" highlight current line number
set cursorline
"override some theme settings
hi clear CursorLine
hi CursorLineNR guifg=#ffffff guibg=#1b2b34
```
