### ISSUE TITLE
Cursorline not work after updated

### ISSUE THREAD

**Issue by jtr109** [mhartington/oceanic-next#58]
# Problems summary

I meet a problem after oceanic-next updated the commit `a1b5774`.

## Expected

- The highlight of current line number not work when vim load at first time. But it works after reload vim config files by `:source ~/.vimrc`, which highlight the line number but disable the highlight of background in current line.

## Environment Information

- terminal: VimR, iTerms 2
- vim/nvim version:
  - nvim: v0.2.1-dev

## Provide a minimal vim rc with less than 50 lines (Required!)

My minimal vim

```vim
" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" set runtimepath+=~/.vim/bundle/oceanic-next
set runtimepath+=~/.local/share/nvim/plugged/oceanic-next
" " For Neovim 0.1.3 and 0.1.4
" let $NVIM_TUI_ENABLE_TRUE_COLOR=1
" Or if you have Neovim >= 0.1.5
if (has("termguicolors"))
 set termguicolors
endif
" Theme
syntax enable
colorscheme OceanicNext
let g:airline_theme='oceanicnext'

```

Full config can be found [here](https://github.com/jtr109/dotfile/tree/master/nvim)

### NeoVim display when load first time

<img width="302" alt="screen shot 2017-07-28 at 16 03 40" src="https://user-images.githubusercontent.com/13946679/28708523-2833190c-73af-11e7-9181-4b4d639d52e0.png">

### Neovim cursorline highlight not work

<img width="254" alt="screen shot 2017-07-28 at 16 09 31" src="https://user-images.githubusercontent.com/13946679/28708501-12f6b238-73af-11e7-9fcb-e1a830b368e0.png">

## By the way

The plugin is awesome. Sorry for not finding out the solution of the bug.

**Comment by jtr109** [comment]
Hi, I saw the CursorLine [has been set into `none` if `g:oceanic_next_highlight_current_line` exists](https://github.com/mhartington/oceanic-next/commit/a1b577419d2f485268f6624e759039a9fb42f3d6#diff-e8a060cc160b2d21d9797efdd57a8fb7R255).

Is this setting changed forever?

After reloading the config, the `exists('g:oceanic_next_highlight_current_line')` will always return true, which cause no color background for CursorLine. Is the value of `g:oceanic_next_highlight_current_line` should be also considered?

Hope for your response. Thanks a lot!

**Comment by mhartington** [comment]
I ended up reverting this, I dont really use the functionality and it's possible to add without having to modify this theme. See https://github.com/mhartington/oceanic-next/issues/55#issuecomment-318854921

**Comment by jtr109** [comment]
Well, I think it is a good choice. :smile:

**Comment by jtr109** [comment]
Thanks for you response!
