### ISSUE TITLE
the "none" of color settings raise error on Vim

### ISSUE THREAD

**Issue by jtr109** [mhartington/oceanic-next#59]
# Problems summary

I meet a problem after oceanic-next updated the commit `a1b5774`.

## Expected

-  An error raised if the function of 'oceanic_next_highlight_current_line' works, which set CursorLine as none.

## Environment Information

- terminal: VimR, iTerms 2
- vim/nvim version:
  - vim: 8.0 (2016 Sep 12, compiled Jul 25 2017 12:36:48)

## Provide a minimal vim rc with less than 50 lines (Required!)

My minimal vim

```vim
" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" set runtimepath+=~/.vim/bundle/oceanic-next
set runtimepath+=~/.local/share/nvim/plugged/oceanic-next
" " For Neovim 0.1.3 and 0.1.4
" let $NVIM_TUI_ENABLE_TRUE_COLOR=1
" Or if you have Neovim >= 0.1.5
if (has("termguicolors"))
 set termguicolors
endif
" Theme
syntax enable
colorscheme OceanicNext
let g:airline_theme='oceanicnext'

```

Full config can be found [here](https://github.com/jtr109/dotfile/tree/master/nvim)

### Vim error when set color as none

![image](https://user-images.githubusercontent.com/13946679/28708004-1024a9ea-73ad-11e7-8bdf-9f1c67dede26.png)

## Reference

The issue rakr/vim-one#34 may be the same problem. But I don't find out the way to fix it.

**Comment by PezCoder** [comment]
I managed to fix this by changing the variable name from 
`let s:none=['none', 'none']`
to 
`let s:none=['NONE', 'NONE']`

**Comment by jtr109** [comment]
Thanks a lot. And Iwill have a try later. :smile:

**Comment by jtr109** [comment]
I think it is a good idea to add a pull request, if it works. @PezCoder

**Comment by PezCoder** [comment]
It works but this update changes the UI for me by having a white undelrine under the cursrorLine & diff sidebar. I've raised an issue for that untill then i'll be using an old commit of this repo. 😄

**Comment by jtr109** [comment]
You could try to overwrite by changing partial variable
