### ISSUE TITLE
Cannot find color scheme 'OceanicNext'

### ISSUE THREAD

**Issue by gnarula** [mhartington/oceanic-next#6]
Not sure if this is because I'm on an older revision of nvim but I get the following error after following the installation instructions:

```
Error detected while processing /home/gaurav/.nvimrc:
line  106:
E185: Cannot find color scheme 'OceanicNext'
Press ENTER or type command to continue
```

A workaround is setting `colorscheme oceanicnext` in ~/.nvimrc and changing `let g:colors_name = "OceanicNext"` to `let g:colors_name = "oceanicnext"` in ~/.nvim/bundle/oceanic-next/colors/oceanicnext.vim

Will update the issue as soon as I update neovim

Current nvim version info:

```
NVIM 0.0.0-alpha+201507262350 (compiled Jul 28 2015 21:07:35)
Commit: ccebc1f8d3b30536bbaab532cc5acc7ba7ec3d4b
```

**Comment by mhartington** [comment]
Hmm, not sure about this one. 
Not sure if the old version of neovim has anything to do with it. What plugin manager are you using? 

My `nvim -v`
NVIM 0.0.0-alpha+201509220803 (compiled Sep 22 2015 14:14:56)
Commit: 1ba081a6735e74446d5e9e05d0fb0bf9cca31f63

**Comment by gnarula** [comment]
I'm using Vundle. I doubt if nvim version has to to anything with it as well. The problem persists for me even after updating to

```
NVIM 0.0.0-alpha+201510021526 (compiled Oct  3 2015 11:36:17)
Commit: f454e4bb11a7a69f1c03325016e3b95cda2fc08e
```

Here's my ~/.nvimrc: https://gist.github.com/gnarula/0344daa92807e9c060e4
The colorscheme is set after vundle#end()

**Comment by bookercodes** [comment]
I get the same error. 

I am using `vim` _not_ `neo vim`, though. Is this supported?

**Comment by gnarula** [comment]
From the neovim [documentation](https://neovim.io/doc/user/syntax.html#:colo):

> :colo[rscheme] {name} Load color scheme {name}.  This searches 'runtimepath'
>           for the file "colors/{name}.vim".  The first one that
>           is found is loaded.

This might be due to the file being named oceanicnext.vim instead of OceanicNext.vim (tried renaming and it works after that).

**Comment by mhartington** [comment]
Just updated the file name, would you mind pulling it down and giving it another try?

**Comment by gnarula** [comment]
Yup, works fine now. Thanks for the update!

**Comment by jcrben** [comment]
In case anyone else encounters this error, for me I had forgotten to run `:PlugInstall` with with `vim-plug`.

**Comment by donifer** [comment]
~Having the same issue. Trying to use it with neovim and Plug. I ran `:PlugInstall` and double checked its installed but I still get `Cannot find color scheme 'OceanicNext'`.~

~I'm sure this is a user error and I'm just missing something, I just don't know what.~

Edit: As expected, this was my bad, I was missing `call plug#end()` 🤦‍♂️

**Comment by john-okeefe** [comment]
I'm also having trouble. I've run :PlugInstall and it says it's installed. I've tried colorscheme OceanicNext, colorscheme oceanicnext. None have worked.

**Comment by gerlim29** [comment]
> I'm also having trouble. I've run :PlugInstall and it says it's installed. I've tried colorscheme OceanicNext, colorscheme oceanicnext. None have worked.

@john-okeefe Any update regarding this issue?

**Comment by norilt** [comment]
@john-okeefe I had the same problem, you have to set `colorscheme OceanicNext` after `call plug#end()`

**Comment by thiggy01** [comment]
I'm using vim with the pathogen plugin manager.
I just cloned ocean-next repo to `~/.vim/bundle/` as usual with pathogen, but when opening vim it still says `cannot find color scheme 'OceanicNext' although it applies the theme correctly.
How to get to install ocean-next with pathogen in vim properly?

**Comment by thiggy01** [comment]
I solved this problem by creating a `~/.vim/colors` folder and putting OceanNext.vim there.
