### ISSUE TITLE
UI breaking on Cursor line

### ISSUE THREAD

**Issue by PezCoder** [mhartington/oceanic-next#61]
# Problems summary
In the recent updates when i enabled the cursor line I'm getting a white line under the highlighted line & the side number bar's colors are mixed up with the main vim panel.

## Expected
This is what i was expecting: 
<img width="843" alt="screen shot 2017-07-29 at 6 53 24 pm" src="https://user-images.githubusercontent.com/8057916/28745134-5b4462b6-748f-11e7-8a1c-25ced3413375.png">
& after `let g:oceanic_next_highlight_current_line = 1`
I though it'll make my line number as white & aligned as defined in this issue, https://github.com/mhartington/oceanic-next/issues/55

but rather I got this:
<img width="963" alt="screen shot 2017-07-29 at 6 47 49 pm" src="https://user-images.githubusercontent.com/8057916/28745139-75544f18-748f-11e7-975d-7d3a18400b76.png">
Notice:
1. Underline under the cursor line
2. side bar bg color is mixed up with the main vim editing panel.

Note: The first screenshot is a checkout of this commit from oceanic next: 914f1a31cb1a3f9265edd5a82373ef6f67a6b97a

## Environment Information

 * terminal: iterm 3.1
 * vim/nvim version: 8.0.6

## Minimal VIMRC
```vim
call plug#begin('~/.vim/plugged')

Plug 'mhartington/oceanic-next'
call plug#end()

set number
set relativenumber
set cursorline
set background=dark
set termguicolors
colorscheme OceanicNext
```

## Thank you
I use this theme everyday in my workflow & this is some really awesome work you've done by making it available for everyone.
I understand that you can't make everyone happy but let me know if this new UI is how you intended or an issue worth fixing.

I'll create a fork if it's the former. 😄

**Comment by jtr109** [comment]
The underline is setted as highlight in terminal, you may find the setting. Maybe it is considered for the elder terminal, or elder vim.

Sorry for not showing the code, because I am typing on mobile.

**Comment by mhartington** [comment]
Hi there, I ended up reverting the cursor line highlight commit. I really don't use the feature, and it can easily be added to a users own rc file. Thanks for kind words, glad this theme is useful to  you 😄
