### ISSUE TITLE
Directory color faded in terminal with true color

### ISSUE THREAD

**Issue by bronzehedwick** [mhartington/oceanic-next#62]
# Problems summary
Opening a Neovim terminal with `set termguicolors` enabled results in a very faded directory color, almost indistinguishable from the file color.

## Expected
Directory colors are distinct from the file color, like they are without `set termguicolors`.

## Environment Information

 * terminal: tested in iTerm2 and Alacritty
 * vim/nvim version:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/config -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/include
Compiled by brew@Sierra-2.local
```

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.config/nvim/plugged/oceanic-next
set termguicolors
colorscheme OceanicNext
```

## The reproduce ways from neovim starting

 1. Start a new terminal: `:terminal`
 2. List some files/directories: `ls`

### With true color enabled
![true-color](https://user-images.githubusercontent.com/637174/34003237-cde789c0-e0c2-11e7-920a-43677a645df0.png)

### With true color disabled
![no-true-color](https://user-images.githubusercontent.com/637174/34003248-d453f5b4-e0c2-11e7-9de0-6fb740a0ffe6.png)

**Comment by mhartington** [comment]
Hmm, good catch. I think the xterm color codes are probably off. I'll have to take some time and try to get the correct values.

**Comment by bronzehedwick** [comment]
Seems like there's a related issue in Neovim that might be playing into this: https://github.com/neovim/neovim/issues/4696

I tried removing all the terminal color codes from the theme, and it works in that the xterm defaults are passed in. It looks like this:

![screen shot 2017-12-14 at 3 08 35 pm](https://user-images.githubusercontent.com/637174/34012173-c2070d2e-e0e0-11e7-9829-2585ba008940.png)
