### ISSUE TITLE
Recommand to use same background in buffer content and line number

### ISSUE THREAD

**Issue by wsdjeg** [mhartington/oceanic-next#64]
@mhartington 

I recommend to use same bg for line number and buffer.

at least the backgroud of line number should same as end of buffer.

**Comment by mhartington** [comment]
Like so? 

I have it locally, just never pushed it  (too much work going on)

![screen shot 2018-01-04 at 9 28 18 am](https://user-images.githubusercontent.com/2835826/34567776-9ea8b2b8-f131-11e7-8b50-5a527a9d7e65.png)

**Comment by wsdjeg** [comment]
sorry, but the picture in the readme should be update.

**Comment by wsdjeg** [comment]
![2018-01-04-22 25 37](https://user-images.githubusercontent.com/13142418/34567916-be6567f2-f129-11e7-9826-3725888e98af.png)

hmm, I need to create a theme in SpaceVim, and hide the end of the buffer.

**Comment by mhartington** [comment]
What "end of the buffer"? I dont understand

**Comment by wsdjeg** [comment]
```
						 {Nvim} *hl-EndOfBuffer*
EndOfBuffer	filler lines (~) after the end of the buffer.
		By default, this is highlighted like |hl-NonText|.
```

**Comment by mhartington** [comment]
Ahh, alright. I just pushed a commit which will highlight this the same as the rest of the buffer. Is that what you want?

**Comment by wsdjeg** [comment]
![2018-01-04-22 33 21](https://user-images.githubusercontent.com/13142418/34568254-d67ea9ec-f12a-11e7-801a-88c07edbcad0.png)

Then `call SpaceVim#api#import('vim#highlight').hide_in_normal('EndOfBuffer')` in SpaceVim, you will see.

![2018-01-04-22 33 26](https://user-images.githubusercontent.com/13142418/34568255-d6babdec-f12a-11e7-8955-cf365890e8f2.png)

**Comment by mhartington** [comment]
I've copied the code for the `hide_in_normal`  function, and it looks like it's working well now. 
<img width="961" alt="screen shot 2018-01-04 at 9 50 21 am" src="https://user-images.githubusercontent.com/2835826/34568759-cee0f94c-f134-11e7-903f-6d97ca19e416.png">

**Comment by wsdjeg** [comment]
@mhartington Thanks, I am reading your virmc, and which statusline do you use?  I have create a build-in statusline for spacevim, :)

**Comment by mhartington** [comment]
Just vim-airline with some settings changed.

**Comment by wsdjeg** [comment]
ok, Thanks!
