### ISSUE TITLE
Misspelled words are not highlighted

### ISSUE THREAD

**Issue by jonsmithers** [mhartington/oceanic-next#66]
# Problems summary

With `set spell`, misspelled words become invisible when I set `termguicolors` (the red highlight disappears).

## Expected

I expect misspelled words to always be visible when `spell` is set.

## Environment Information

| | `notermguicolors` | `termguicolors` |
|--- | --- | --- |
| vim 8.0 | ![screenshot from 2018-01-31 20-24-24](https://user-images.githubusercontent.com/2660313/35656380-24a8c5c6-06c5-11e8-97f5-3922de48f43b.png) | ![screenshot from 2018-01-31 20-24-56](https://user-images.githubusercontent.com/2660313/35656381-24b8374a-06c5-11e8-91be-25364ceb26a8.png) |
| neovim 0.2.2 | ![screenshot from 2018-01-31 20-40-59](https://user-images.githubusercontent.com/2660313/35656821-59a45f36-06c7-11e8-909f-65b448c0b081.png) |  ![screenshot from 2018-01-31 20-41-43](https://user-images.githubusercontent.com/2660313/35656839-713182dc-06c7-11e8-877e-43a7ce151cc7.png) |

As you can see, the issue only exists in vim 8.0 with `termguicolors` enabled (do you support vim 8?)

 * terminal: the screenshots above were produced in Tilix, but gnome-terminal and iTerm seem to behave the same way
 * vim/nvim version: vim 8.0, nvim 0.2.2

## minimal vimrc

```vim
set runtimepath^=~/.vim/plugged/oceanic-next/
colorscheme OceanicNext
set spell
```

## Reproduction Steps

1. `vim -u minimalvimrc`
2. Type some misspelled words. They are highlighted red.
3. `:set termguicolors`
4. Red highlights on misspelled words.

**Comment by jonsmithers** [comment]
....well, I can repeat this behavior on the default vim theme, so it clearly has nothing to do with oceaic-next. I guess it's purely a vim 8 thing.

**Comment by mhartington** [comment]
Hey sorry for the radio silence on my end, I've been traveling for work. Glad to see this is all sorted out

**Comment by jonsmithers** [comment]
All good, I appreciate the support! Sorry for the misguided issue.
