### ISSUE TITLE
Incorrect colors with minimal setup

### ISSUE THREAD

**Issue by jlin816** [mhartington/oceanic-next#69]
# Problems summary
The OceanicNext colors were working for me at some point, but I did or updated something recently that totally changed my color scheme, and I can't seem to revert it, even with a minimal setup.

## Expected
The colors in the `README` screenshot.

## Environment Information

 * terminal: iTerm 2 Build 3.0.14
 * vim/nvim version: vim 8.0
* macOS: High Sierra 10.13.3

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
set nocompatible              " be iMproved, required
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'mhartington/oceanic-next'

call vundle#end()
filetype plugin indent on

if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme OceanicNext
```

## The reproduce ways from neovim starting

Simply opening vim.

## Screen shot (if possible)
<img width="482" alt="screen shot 2018-05-05 at 10 52 02 am" src="https://user-images.githubusercontent.com/4398313/39664517-5e7e5938-5052-11e8-929e-7d69f8ce1b42.png">

**Comment by mhartington** [comment]
Hi! Sorry for the delay!

Hm, I'm not able to replicate this on my end. 

Tested with Vim 8, iterm 3.1 and kitty term.

![screen shot 2018-05-18 at 9 47 01 am](https://user-images.githubusercontent.com/2835826/40238245-b0cbe178-5a80-11e8-983b-e0a32323bb05.png)

Used same config as your, though with vim-plug, not vundle. 

I would your terminal settings see if xterm variable is being set to something that support true colors. 

```shell

curl https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh | bash
```

**Comment by dannytranlx** [comment]
Did you test with zsh? I reproduce as well on iTerm 3.1.6 and neovim 0.2.0 on macOS 10.13.4

**Comment by mhartington** [comment]
zsh is a terminal program, not the terminal emulator, so it has no control over colors. Again, stated in my previous comment, the screenshot is iterm on a mac. I tested different terminal emulators, Vim and Neovim, and was not able to reproduce. Please provide anymore details (minimal vimrc) to debug further.

**Comment by skriems** [comment]
fwiw, I'm pretty sure the commit in feb had some undesired sideeffects. I'm using transparent background and it was working before but now only the lines with text have transparent background. I never found the time to track this down.
I hope I can spend some time next week and will open an issue if necessary.

**Comment by dannytranlx** [comment]
~Confirmed, I reverted to f2f5c7eb7b5edc32bb2a8850f78447ef716d5660 the one before that one in feb and everything is back in order!~

Actually, I lied. It's fine on `master` on iTerm directly, going through `tmux` still reproduce.

EDIT: Fixed my issue with #51

**Comment by olalonde** [comment]
I have the same issue and it does seem related to tmux... I'm using iTerm2 with Solarized Dark theme and neovim.

Expected (from mhartington/oceanic-next README.md):

![expected](https://user-images.githubusercontent.com/416585/46966267-cf5c0980-d0df-11e8-83f1-873c27847cb5.png)

How it looks on my computer when not inside tmux:

<img width="921" alt="screenshot 2018-10-16 01 04 03" src="https://user-images.githubusercontent.com/416585/46966194-96239980-d0df-11e8-923e-022d1ddd3854.png">

How it looks on my computer when inside tmux:

<img width="922" alt="screenshot 2018-10-16 01 04 39" src="https://user-images.githubusercontent.com/416585/46966290-e3a00680-d0df-11e8-93e6-f10bdd5ccc76.png">

**Comment by olalonde** [comment]
Like mentioned in #51 , adding this to my `.tmux.conf` fixed the problem:

```tmux
# Fix vim theme issue
# https://github.com/mhartington/oceanic-next/issues/51
set -ga terminal-overrides ",xterm-256color:Tc"
```
