### ISSUE TITLE
Colors not loading correctly

### ISSUE THREAD

**Issue by bendyorke** [mhartington/oceanic-next#7]
I tried using oceanic-next with the public release of neovim, however I'm getting some quite undesirable results.  My `.nvimrc` looks like this (should have all the lines related to `oceanic-next`):
![image](https://cloud.githubusercontent.com/assets/3488879/10892402/d529774a-8168-11e5-9707-db1d494ec9b7.png)
And javascript files look like this (stole parts of your example image so it's easier to compare):
![image](https://cloud.githubusercontent.com/assets/3488879/10892515/7670f600-8169-11e5-93e6-dd368c3cb35b.png)

I'm using iTerm2 3.0 beta (I've tried all the terminal types), your iterm color profile, and neovim.  Any idea what might be causing the issue?

**Comment by mhartington** [comment]
Hmm, not sure you need that extra rtp line. If you're using vundle, it should already be sourced. 

Overall. Not sure. I have neovim and iterm nighties. Could you post your neovim and iterm version?

**Comment by mhartington** [comment]
Mind testing this out? 

https://github.com/neovim/neovim/wiki/Following-HEAD#20151026

**Comment by FuzzOli87** [comment]
I'm also experiencing this discoloration. 

![screen shot 2015-11-06 at 11 00 01 am](https://cloud.githubusercontent.com/assets/12246915/11002959/92ee979c-8475-11e5-8ff7-fd87fdc9633e.png)

I've reconfigured my nvim to use a symlink to the new config directory. 

I'm running on iTerm nightly Build 2.9.20151105-nightly
And Neovim from HEAD NVIM v0.1.0-12-g9499432 (compiled Nov  6 2015 10:58:32)

I'm using the OceanicNext iTerm color scheme as well. No discoloration there.
![screen shot 2015-11-06 at 11 19 58 am](https://cloud.githubusercontent.com/assets/12246915/11003484/5fbb1b90-8478-11e5-87c3-e36995eaabe3.png)

**Comment by mhartington** [comment]
Hmm that looks like it's displaying correctly

**Comment by FuzzOli87** [comment]
![screen shot 2015-11-06 at 11 50 04 am](https://cloud.githubusercontent.com/assets/12246915/11004214/8d41cd58-847c-11e5-95ec-aedbe8b11f8f.png)

You can kind of see the color difference between the iTerm background color and Neovim in the corner.
Yeah it does look darker in the images I take compared to what I see on my monitor. Still though it looks more like a washed out dark-blue green that the mid-bright blue in the README

**Comment by mhartington** [comment]
Hmm, would you mind posting the colors of your terminal? I'm not sure how I could go about debugging this one. Here are some screen shots from my terminal. 

Iterm 2 nightly builds: Build 2.9.20151105-nightly
Neovim: NVIM v0.1.0-12-g9499432 (compiled Nov  6 2015 17:03:38)

<img width="324" alt="screen shot 2015-11-06 at 4 46 15 pm" src="https://cloud.githubusercontent.com/assets/2835826/11009867/87249604-84a8-11e5-8681-5ef47895bd3d.png">
<img width="203" alt="screen shot 2015-11-06 at 4 47 27 pm" src="https://cloud.githubusercontent.com/assets/2835826/11009865/8723afbe-84a8-11e5-8768-66a0f7f02d09.png">

**Comment by FuzzOli87** [comment]
Yeah this is weird. I had an issue like this in Chrome on ArchLinux where the borders on components inside web pages were too light. After much debugging and screenshots(people telling me they don't see the issue) I found out it was my monitor configurations.

I'm looking at your screenshots and they look a nice dark blue, not as light as the one in the OP. Pretty similar to what I see. On my Mac it looks about the same color as your terminal images. However, if the colors were supposed to be the same as the iTerm, then they are off. Here is a pic of my iTerm color-scheme which is just the OceanicNext for iTerm2 scheme.

<img width="668" alt="screen shot 2015-11-06 at 11 17 52 pm" src="https://cloud.githubusercontent.com/assets/12246915/11013682/cdd4a4d4-84dc-11e5-8570-57e1ccdc9c3a.png">

How did you get that sweet bottom status line with the time and everything?

**Comment by mhartington** [comment]
That's my tmux statusline https://github.com/mhartington/dotfiles/blob/master/config/tmux-status.conf

Ahh I think I may know whats up. Try downloading this iterm theme.

https://github.com/mhartington/dotfiles/blob/master/config/oceanic-dark.itermcolors

I tweaked the base background color a little bit in vim and iterm but may have forgotten to update it.... :grin: 

Let me know if this helps

**Comment by FuzzOli87** [comment]
Tried on the new colors and I see them match now. I guess this was all just a massive misunderstanding! I also learned about vim-swoop because of your dotfiles. Thanks for the help!

**Comment by mhartington** [comment]
Wonderful! I'll make sure to update the iterm repo.

**Comment by bendyorke** [comment]
Hey! Sorry I totally dropped the ball on this one.  Forgot I had even raised an issue!  

I switched over to the new config directory structure (thus removing the need for all the `rtp` calls), and reinstalled all my packages via `vim-plug`.  I have the latest install of neovim (v0.1.0-28-g94015cd) and iterm nighties (2.9.20151105-nightly).

Uninstalled everything and set it back up, and now I'm seeing some different colors - not sure if they are correct or not.  You attached some screenshots in this thread with different colors than shown in the readme - has the colorscheme changed?  It's not really a dark blue anymore, it's just a dark grey.

Terminal
<img width="1440" alt="screen shot 2015-11-09 at 9 00 55 am" src="https://cloud.githubusercontent.com/assets/3488879/11036905/ab7c6486-86c0-11e5-9df9-326457ed3134.png">
`init.vim`
<img width="1440" alt="screen shot 2015-11-09 at 9 02 06 am" src="https://cloud.githubusercontent.com/assets/3488879/11036913/af36795e-86c0-11e5-9726-b0f32cd95c4b.png">
JavaScript file (webpack-dev-middleware)
<img width="1440" alt="screen shot 2015-11-09 at 9 02 45 am" src="https://cloud.githubusercontent.com/assets/3488879/11036915/b165e7f0-86c0-11e5-97c8-3a17ed6f8e4c.png">

**Comment by bendyorke** [comment]
Ah yes, it's just that one background color that changed.  I added a pull request (#8) that just checks a if a varaible exists.  Nothing fancy but it worked for me!

**Comment by mhartington** [comment]
ahh, alright. Hmm, this is more of personal choice if anything. 

Looking at the original theme from sublime text.

![](https://raw.githubusercontent.com/voronianski/oceanic-next-theme/master/screenshots/extended-class.png)

And then this theme with the darker background. 
![screen shot 2015-11-09 at 11 28 29 am](https://cloud.githubusercontent.com/assets/2835826/11039311/0daa7436-86d5-11e5-8c40-8a635d9bb092.png)
