### ISSUE TITLE
How to enable transparency?

### ISSUE THREAD

**Issue by concatime** [mhartington/oceanic-next#71]
# Problems summary
It would be awesome if you provide this option like [this](//github.com/NLKNguyen/papercolor-theme#theme-options).
My [init.vim](//github.com/concatime/dotfiles/blob/master/workstation/home/vm/.config/nvim/init.vim).

## Environment Information

 * terminal: QTerminal 0.9.0
 * vim/nvim version: NVIM v0.3.0

**Comment by kabasakalis** [comment]
Agree with @concatime . I use terminator terminal with background image, and the theme overrides the background image in empty lines.

**Comment by marco-fp** [comment]
Does the background color look different to you in Terminator? It does for me :/

**Comment by itsdeadguy** [comment]
I have achieved transparency in neovim 0.3.8 like so:

```
set termguicolors
let g:oceanic_next_terminal_italic = 1
colo OceanicNext

hi! VertSplit ctermbg=NONE ctermfg=NONE guibg=NONE guifg=#080808
hi! Comment cterm=italic ctermbg=NONE guibg=NONE
hi! Normal ctermbg=NONE guibg=NONE
hi! NonText ctermbg=NONE guibg=NONE
hi! LineNr guibg=NONE
hi! CursorLineNr ctermbg=236 ctermfg=NONE guibg=#303030
hi! CursorLine ctermbg=236 ctermfg=NONE guibg=#303030
hi! SignColumn ctermbg=NONE guibg=NONE
hi! Folded ctermbg=NONE guibg=NONE
hi! EndOfBuffer ctermbg=NONE ctermfg=NONE guibg=NONE guifg=#080808
hi! WildMenu ctermfg=226 ctermbg=0 guifg=#ffff00 guibg=#000000
```

**Comment by ryeballar** [comment]
@CadaverLab it seems that your solution didn't work for me. I took inspiration from this [gist](https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f). Here's my config:
```
augroup MyColors
    autocmd!
    autocmd ColorScheme * highlight Normal ctermbg=NONE guibg=NONE
                      \ | highlight EndOfBuffer ctermbg=NONE guibg=NONE
                      \ | highlight NonText ctermbg=NONE guibg=NONE
                      \ | highlight LineNr ctermbg=NONE guibg=NONE
                      \ | highlight CursorLine ctermbg=NONE guibg=NONE
                      \ | highlight SpecialKey ctermbg=NONE guibg=NONE
                      \ | highlight FoldColumn ctermbg=NONE guibg=NONE
                      \ | highlight VertSplit ctermbg=NONE guibg=NONE
                      \ | highlight Visual term=reverse cterm=reverse guibg=Grey
augroup END

if (has("termguicolors"))
 set termguicolors
endif

syntax enable
colorscheme OceanicNext
```

**Comment by mhartington** [comment]
Sorry for the silence on my end. Can this be closed? Looks like things should support transparency if your terminal supports it.

<img width="1399" alt="Screen Shot 2020-11-05 at 8 43 46 PM" src="https://user-images.githubusercontent.com/2835826/98316037-9b463080-1fa7-11eb-94f2-6a1dda4f7f58.png">

**Comment by concatime** [comment]
Probably. I’ve changed my setup, so I cannot test right now. Thank you tho!
