### ISSUE TITLE
E254: Cannot allocate colour None

### ISSUE THREAD

**Issue by kud** [mhartington/oceanic-next#75]
https://github.com/mhartington/oceanic-next/blob/2380a559a1b522e4e47e1ef5f90cfa73ac2cc823/colors/OceanicNext.vim#L46 rises an error.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/655838/49078143-87331980-f23d-11e8-8ad9-abc9a9b94b6a.png">

**Comment by kud** [comment]
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 24 2018 19:11:56)

**Comment by mhartington** [comment]
Fixed via https://github.com/mhartington/oceanic-next/commit/a869ef778b4707b0c1bd0e5834304400292399f0

**Comment by kud** [comment]
🙌
