### ISSUE TITLE
Installation for vim 7 / vim 8 not accurate on Google Cloud Shell

### ISSUE THREAD

**Issue by ghost** [mhartington/oceanic-next#76]
# Problems summary
I needed to use the instruction for vim 7 even tough vim 8 is installed.

## Expected
Use vim 8 instruction with vim 8 installed.

## Environment Information

 * terminal: cloudshell inside tmux
 * vim/nvim version: vim 8.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Loading Plugin
call plug#begin('~/.vim/plugged')
Plug ('mhartington/oceanic-next')
call plug#end()

" Theme
syntax enable
set t_Co=256
colorscheme OceanicNext
```

## The reproduce ways from neovim starting

 1. Go to https://console.cloud.google.com (You need a Google Account for that - it's free)
 2. Put config above into `.vimrc`
 3. Start `vim .vimrc` (for example)

## Screen shot (if possible)

Looked like this (black and white) with the vim 8 installation instructions. 

![ksfya](https://user-images.githubusercontent.com/45097514/49750150-802ef100-fcaa-11e8-87b8-5a2e17f0e45e.png)

And looks like this without any additional colorscheme / theme (like default on Google Cloud Shell):

![4lht8](https://user-images.githubusercontent.com/45097514/49750258-b10f2600-fcaa-11e8-85f4-eb41bb946363.png)

With the vim 7 installation instructions looks finally like it should:

![screenshot 2018-12-10 at 18 38 02](https://user-images.githubusercontent.com/45097514/49750293-cab06d80-fcaa-11e8-9f04-d649b0e9b298.png)

## Possible Solution
I am not sure if a simple mention in the `README.md` is enough. 

Credits to [Christian Brabandt](https://vi.stackexchange.com/users/71/christian-brabandt)  who gave me the right hint on [StackExchange](https://vi.stackexchange.com/questions/18219/no-color-in-vim-while-using-google-cloud-shell).

**Comment by mhartington** [comment]
Probably an issue with it being an early version of vim 8 or just that terminal emulator being used does not fully support true colors. If you want to send a PR, that would be great, but I think this is a very specific/niche type of issue.

**Comment by ghost** [comment]
See #77
