### ISSUE TITLE
How to set the background color, it looks like ...

### ISSUE THREAD

**Issue by qingdujun** [mhartington/oceanic-next#81]
# Problems summary
```
How to set the background color, it looks like `Click`.
```

[Click](http://vimcolors.com/377/OceanicNext/dark)

## Expected

```
The background look like http://vimcolors.com/377/OceanicNext/dark
```

## Environment Information

 * terminal: `/bin/bash`
 * vim/nvim version:

```
qingdujundeMacBook-Pro:~ qingdujun$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:46)
macOS version
```

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/oceanic-next
```

My `~/.vimrc`, and the full informations you can see [Here](https://github.com/qingdujun/dotvimrc/blob/master/.vimrc) and [issue](https://github.com/vim-airline/vim-airline-themes/issues/171)

```
Plug 'mhartington/oceanic-next'

...

" Theme
 syntax enable
" for vim 7
 set t_Co=256

" for vim 8
 if (has("termguicolors"))
  set termguicolors
 endif

colorscheme OceanicNext
```

## The reproduce ways from neovim starting

 1. foo
 2. bar
 3. baz

## Screen shot (if possible)

![屏幕快照 2019-04-10 下午4 19 13](https://user-images.githubusercontent.com/9897658/55866840-c2faca00-5bb3-11e9-9a0d-c327a0110945.png)

**Comment by mhartington** [comment]
what terimnal are you using? iterm? Apple's built-in terminal? From the looks of it, the terminal might not support true colors, meaning that it's falling back to the older ansi colors, which in turn are dependent on your terminals color settings.

**Comment by qingdujun** [comment]
> what terimnal are you using? iterm? Apple's built-in terminal? From the looks of it, the terminal might not support true colors, meaning that it's falling back to the older ansi colors, which in turn are dependent on your terminals color settings.

Yes, Apple's built-in terminal.

I have changed to `neovim`. But, where shoud I put my config or `.vimrc`?

**Comment by qingdujun** [comment]
Sorry, I have found it.
```bash
: help vimrc
```
A file that contains initialization commands is generically called a "vimrc" or config file.  Each line in a vimrc file is executed as an Ex command line.  See also vimrc-intro and base-directories.

The Nvim config file is named "init.vim", located at:
```
Unix            ~/.config/nvim/init.vim
Windows         ~/AppData/Local/nvim/init.vim
```
Or if $XDG_CONFIG_HOME is defined:
```
$XDG_CONFIG_HOME/nvim/init.vim
```

So cool!

![屏幕快照 2019-04-10 下午8 17 44](https://user-images.githubusercontent.com/9897658/55877877-bdaa7900-5bcd-11e9-8d93-2c405db52ba2.png)
