### ISSUE TITLE
Incorrect colors on neovim

### ISSUE THREAD

**Issue by Dbz** [mhartington/oceanic-next#82]
# Problems summary

Colors look like:

![image](https://user-images.githubusercontent.com/628429/73897570-57b56f00-483b-11ea-9424-25ff371a511d.png)

## Expected

Colors to look like:

![image](https://user-images.githubusercontent.com/628429/73897602-774c9780-483b-11ea-94af-a7422aa3301b.png)

## Environment Information

 * terminal: iterm2
 * vim/nvim version:

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/config -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/src/nvim/auto -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
```

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
""
" Set the color scheme and custom colors
" For Neovim 0.1.3 and 0.1.4
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
" Or if you have Neovim >= 0.1.5
if (has("termguicolors"))
 set termguicolors
endif
" syntax enable
colorscheme OceanicNext
" colorscheme one
" set background=dark
" Set the cursors color when on an opening/closing brace
highlight MatchParen ctermfg=lightgray ctermbg=darkgray
" Set the highlight color
highlight Visual term=reverse cterm=reverse guibg=Grey
```

## The reproduce ways from neovim starting

Open a file (in this case I have open my vimrc and also a golang file

**Comment by Dbz** [comment]
I want to say a quick thank you for creating this color scheme. I think it's really pretty, and I'd love to adopt it.

**Comment by Dbz** [comment]
@mhartington is there any chance you have a moment to help me with this?

**Comment by mhartington** [comment]
This theme is inspired/derived from the original ocean-next for sublime. But sublime and vim have very different syntax highlighting approaches. Not everything is going to be a 1:1 match.
