### ISSUE TITLE
background is the wrong color

### ISSUE THREAD

**Issue by KyleMcB** [mhartington/oceanic-next#85]
# Problems summary
Background color is not what I expected from preview image

## Expected

background color should have some level of blue.

## Environment Information

 * terminal: gnome-terminal (default fedora 31 settings)
 * vim/nvim version:
nvim 0.4.3

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
"Plugins
call plug#begin('~/.config/nvim/plugged')
Plug 'mhartington/oceanic-next'
call plug#end()
syntax on
colorscheme OceanicNext

```

## The reproduce ways from neovim starting

every file I open has a dark gray background #262626
This might not be a problem with this specific colorscheme, this also happens with one and onedark colorschemes they also have a dark blue/grey background. I also had this problem on clear linux (I switched to fedora recently) I'm a new neovim user. I still have a lot to learn, so maybe I am doing something wrong that is obvious, but I would really appreciate the help. The only color scheme that has set the background to the color displayed by the preview image that I have found is dracula.

The terminal and neovim look like they support truecolor and changing the terminal color settings in gnome-terminal don't affect the background-color

other terminals I've tried
xterm has the same colors as gnome-terminal 
urxvt breaks the theme and makes it black on white. 

I read the 4 previous issues related to background color and still could not resolve this issue.

## Screen shot (if possible)

![Screenshot from 2020-03-20 12-23-18](https://user-images.githubusercontent.com/52633531/77201162-43ef6080-6aa9-11ea-99b1-9e7ba62d525e.png)

**Comment by mhartington** [comment]
Please enable true color support in neovim

https://github.com/mhartington/oceanic-next/blob/master/README.md#installation

**Comment by KyleMcB** [comment]
thank you very much. I'm sorry that was such an obvious fix.
