### ISSUE TITLE
Incorrect color

### ISSUE THREAD

**Issue by pirey** [mhartington/oceanic-next#89]
# Problems summary
I love this colorscheme and thought to give it a try, but i have struggled to set it up cause my color doesn't look like the picture shown in readme.

## Expected
I want to have my colors the same as picture shown in the readme.

## Environment Information

 * terminal: kitty
 * vim/nvim version: vim 8.2 

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call plug#begin('~/.vim/plugged')

Plug 'mhartington/oceanic-next'
Plug 'othree/yajs.vim'
Plug 'othree/html5.vim'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'vim-airline/vim-airline'

call plug#end()


" Theme
 syntax enable
" for vim 7
" set t_Co=256

" for vim 8
 if (has("termguicolors"))
  set termguicolors
 endif

colorscheme OceanicNext
let g:airline_theme='oceanicnext'
```

## Screen shot (if possible)
Color doesn't match example
![Screenshot from 2020-07-15 11-35-21](https://user-images.githubusercontent.com/10344542/87503550-c3bfbd00-c68e-11ea-90d7-6e9c3c93db43.png)

**Comment by ghost** [comment]
Have the same issue, colors are obviously not in oceanic theme

![Снимок экрана 2020-07-29 в 00 16 00](https://user-images.githubusercontent.com/29314058/88722913-b267bd80-d130-11ea-9636-c4dad45aaa22.png)

**Comment by adrian5** [comment]
@ysizarie Your screenshot looks suspiciously like the Oceanic Next palette in 256-color mode. If `termguicolors` wasn't already staring at me, that would've been the first suggestion.

**Comment by mhartington** [comment]
@ysizarie are you sure your terminal supports true colors? Like @adrian5 says, it looks like the 256 color mode.
