### ISSUE TITLE
Colors don't seem to be loading correctly

### ISSUE THREAD

**Issue by gblock0** [mhartington/oceanic-next#9]
Hi,

I'm trying to load your colorscheme in neovim with true colors and this is what my init.vim file looks like.

![screen shot 2015-12-09 at 6 02 31 pm](https://cloud.githubusercontent.com/assets/1434705/11702800/329cf1ba-9e9f-11e5-9918-42ca7b2f32b0.png)

I'm setting the color scheme after loading all my plugins and starting neovim with the true-color flag.

I also commented out the rest of my color schemes in my plugin file to see if something was conflicting but that didn't help.

Have you experienced this?

I'm on OS X 10.11.2 by the way.

Neovim version:

```
NVIM 0.1.0 (compiled Nov  1 2015 16:15:29)
Commit: v0.1.0
Build type: RelWithDebInfo
```

**Comment by gblock0** [comment]
I have loaded the iterm colorscheme, but that didn't seem to help.

**Comment by mhartington** [comment]
Hmm, interesting. Let me take a look tonight. Is there a minimal init.vim I could look at?

**Comment by gblock0** [comment]
Thanks. You can checkout my dotfiles [here](https://github.com/gblock0/dotfiles). It is under the `config/nvim` folders.

**Comment by mhartington** [comment]
Created a minimal init.vim, but it seems to be working fine for me.

``` viml
call plug#begin('~/.config/nvim/plugged')
Plug 'mhartington/oceanic-next'
Plug 'othree/yajs.vim'
call plug#end()

syntax enable
set number

let $NVIM_TUI_ENABLE_TRUE_COLOR=1

colorscheme OceanicNext
set background=dark
```

<img width="1680" alt="screen shot 2015-12-13 at 11 24 53 am" src="https://cloud.githubusercontent.com/assets/2835826/11767956/2f2b98d4-a18c-11e5-9371-902ca40c7ce3.png">

My guess is that the alias you have to enable true colors could be causing issues. So in my init.vim, I just add the variable sit there, and it works fine. 

Update: Loaded your exact neovim setup, confirmed that adding 

``` viml
" Color Scheme Settings
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
colorscheme OceanicNext
set background=dark
```

Fixes the issues.

**Comment by gblock0** [comment]
Hmm... still not working for me. Must be some other settings I need to play with. Thanks for checking it out.

**Comment by mhartington** [comment]
I'd try starting with a minimal init and then slowly adding things from there.

**Comment by gblock0** [comment]
Yep. That's my plan.

**Comment by charliewilco** [comment]
@gblock0 did you ever figure out this problem? really interested to hear your results

**Comment by gblock0** [comment]
@charlespeters I wasn't able to figure it out. I tried using the minimal init.vim that @mhartington suggested and I was still seeing the color scheme wrong. I've looked through my zsh settings and I didn't see anything that would have changed the color. I've tried updating my iTerm colors, but nothing. 

I don't really know what else to try at the moment, but I'm assuming it's some color setting on my computer that I need to figure out. If I figure out what it is I will update it here.

**Comment by mhartington** [comment]
@gblock0 do you have a terminal that can support true colors? For OSX it's iterm nightly only right now.

**Comment by gblock0** [comment]
Yes I have the nightly. I updated it last night to be sure.

**Comment by mhartington** [comment]
@charlespeters are you having issues as well?

**Comment by charliewilco** [comment]
yes

iterm2
Build 2.9.20151111

neovim
NVIM v0.1.1-79-g77c0f9a (compiled Dec 14 2015 00:33:16)

**Comment by charliewilco** [comment]
and for what it's worth this is my vimrc
https://github.com/charlespeters/dotfiles/blob/develop/vimrc

**Comment by mhartington** [comment]
@charlespeters Hm, not seeing anything out of the ordinary with your vimrc. Do you have a screen shot? So far in regular vim, everything's checking out. 

For neovim, this won't work since it doesn't follow the new setup. `$HOME/.config/nvim/init.vim` is now the new `nvimrc`

<img width="656" alt="screen shot 2015-12-16 at 9 40 23 am" src="https://cloud.githubusercontent.com/assets/2835826/11843718/13f420be-a3d9-11e5-9b2e-efcc5169f53b.png">

**Comment by charliewilco** [comment]
<img width="1679" alt="screenshot 2015-12-26 21 00 50" src="https://cloud.githubusercontent.com/assets/4588060/12008907/c94663cc-ac13-11e5-9d8d-3fa2814e311a.png">

**Comment by charliewilco** [comment]
for point of interest

the latest general release of iterm is on the left
the nightly is on the right

<img width="1680" alt="screenshot 2015-12-26 22 09 02" src="https://cloud.githubusercontent.com/assets/4588060/12009068/6921411a-ac1d-11e5-9fc0-fc10726b69f5.png">

**Comment by mhartington** [comment]
Yeah iterm nightly build handles the theme the best since t supports true colors

**Comment by gblock0** [comment]
@charlespeters were you ever able to figure out this issue?

**Comment by charliewilco** [comment]
not really, i just switched to regular vim and it seems to work nicely.
