### ISSUE TITLE
Weird highlight of the "brackets" in floating window

### ISSUE THREAD

**Issue by thekaganugur** [mhartington/oceanic-next#91]
# Problems summary

I'm using CoC, when I hover to get documentation via float window, the parentheses background color is weird as need in screenshots.

## Expected

Proper background color for parentheses on the floating window.

## Environment Information

 * terminal: iTerm2 3.3.12 
 * vim/nvim version:NVIM v0.4.4

## Minimal vim rc

```vim
call plug#begin('~/.nvim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'sheerun/vim-polyglot'
  Plug 'mhartington/oceanic-next'
call plug#end()

set termguicolors
colorscheme OceanicNext


" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
```

## The reproduce ways from neovim

 1. Install dependecys
 2. Write console.log() inside an JS/TS file
 3. How with 'K' over log

## Screen shot

![image](https://user-images.githubusercontent.com/28161197/97045208-04787d80-157e-11eb-96c7-6fcd9fd9b430.png)

## Related

https://github.com/neoclide/coc.nvim/issues/1248
https://github.com/joshdick/onedark.vim/issues/197#issuecomment-574422967
https://github.com/scalameta/coc-metals/issues/309

**Comment by mhartington** [comment]
I just merged a coc related PR, which I think fixes this? I don't use coc (since nvim has it's lsp built in). Can you pull the latest and test it out?

**Comment by thekaganugur** [comment]
Yes, it is fixed sorry for the really late reply.  :)
