### ISSUE TITLE
 background color no longer works.

### ISSUE THREAD

**Issue by tofulm** [mhartington/oceanic-next#94]
# Problems summary
since #92 ,  the background color no longer works.

## Environment Information

 * terminal: kitty / gnome-terminal / alacrity
 * nvim version: 0.4.4

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'mhartington/oceanic-next'
call plug#end()
syntax enable
if (has("termguicolors"))
    set termguicolors
endif
colorscheme OceanicNext
```

## Screen shot (if possible)
![2020-11-08-100446_1920x1080_scrot](https://user-images.githubusercontent.com/2989137/98461225-c6e53880-21aa-11eb-961d-f9ba153901be.png)

**Comment by hillaryychan** [comment]
Had the same issue as well. 

It looks like it's because the background value for `Normal` is set to `s:none` instead of `s:base00` in the latest PR (See [OceanicNext.vim](https://github.com/mhartington/oceanic-next/blob/master/colors/OceanicNext.vim#L97)).

**Comment by tofulm** [comment]
thanks
