### ISSUE TITLE
'normal' text is now drawn as 100% white

### ISSUE THREAD

**Issue by cmyr** [mhartington/oceanic-next#95]
# Problems summary

Normal text is now drawn fully white; pure white text is very bright and hard to read. 
A quick bisect tracks this down to e58e5ee, although I haven't dug in any deeper than that.

## Expected

Normal text is drawn a light grey (`#B3B8C3`?).

## Environment Information

 * terminal: iterm2
 * vim/nvim version: NVIM v0.4.4

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/.dotfiles/nvim/plugged/oceanic-next

if (has("termguicolors"))
  set termguicolors
endif

" Theme
syntax enable
colorscheme OceanicNext

```

## The reproduce ways from neovim starting

 1. Open neovim

## Screen shot (if possible)

before:

![Screen Shot 2020-11-18 at 1 27 23 PM](https://user-images.githubusercontent.com/3330916/99571809-cc5c3300-29a1-11eb-97c7-cef80977626c.png)

after:

![Screen Shot 2020-11-18 at 1 27 59 PM](https://user-images.githubusercontent.com/3330916/99571876-e1d15d00-29a1-11eb-8bf3-be50d47e318b.png)

Let me know if I'm missing anything or can provide any more information, and thanks for all your work!

**Comment by mhartington** [comment]
Hey there! This was an intensional change. I wanted the text to be clearer and stand out more. If you want to revert back, you can add 

```viml
hi Normal guifg=#d8dee9
```

In your init.

**Comment by cmyr** [comment]
Huh. Okay, I respect your authorship,  but I will register my disagreement; I find the contrast just too aggressive. Your fix works fine though, so no worries.

Thanks!

**Comment by 0xC0FFEE** [comment]
I agree with @cmyr about the contrast being too aggressive. So thank you very much for reverting this @mhartington and also providing a work around prior to that :-).

Btw: awesome theme. Thanks for creating/maintaining it :heart:

**Comment by benwoodward** [comment]
Thanks for reverting this, for me Oceanic Next is one of the few themes that has the contrast dialled in perfectly.  Thanks for your work on this—looking forward to the tree-sitter compatibility I saw you mention on reddit.

**Comment by benwoodward** [comment]
@mhartington I have https://github.com/mhartington/oceanic-next/commit/29d694b9f6323c90fb0f3f54239090370caa99fb installed, and the text is still displaying as complete white: 

![image](https://user-images.githubusercontent.com/1472981/99868510-050d3e00-2c28-11eb-9af0-d15c15198ce4.png)
![image](https://user-images.githubusercontent.com/1472981/99868513-0dfe0f80-2c28-11eb-8b15-5361081fbcd3.png)

I've tried adding:

```
  hi Normal guifg=#d8dee9
  hi Normal ctermfg=235
```

..at the end of my `init.vim` but that doesn't work. Not sure what's going on here?

**Comment by mhartington** [comment]
Doesn't appear to be full white to me, so not sure. But you open a new issue and provide a minimal vimrc, I can look into.

**Comment by benwoodward** [comment]
@mhartington I've just compared the diffs and found the issue:

At https://github.com/mhartington/oceanic-next/commit/08158eec24cd154afd1623686aeb336fad580be7 (the latest branch with the original 'white' value) the color for `Normal` was `base05`. https://github.com/mhartington/oceanic-next/blob/08158eec24cd154afd1623686aeb336fad580be7/colors/OceanicNext.vim#L97

In https://github.com/mhartington/oceanic-next/commit/e58e5ee4ecbb5cf8f671f389db55d43dbb592f58 it was changed to `s:white`: https://github.com/mhartington/oceanic-next/blob/e58e5ee4ecbb5cf8f671f389db55d43dbb592f58/colors/OceanicNext.vim#L97

And in https://github.com/mhartington/oceanic-next/commit/29d694b9f6323c90fb0f3f54239090370caa99fb it wasn't reverted to `base05`, but `base07`, which is not full-white, but much brighter than the original `base05` color. https://github.com/mhartington/oceanic-next/blob/29d694b9f6323c90fb0f3f54239090370caa99fb/colors/OceanicNext.vim#L97

**Comment by cmyr** [comment]
To chime in: yes, the white at `HEAD` is currently whiter than it was at 08158ee, but less white than it was when I opened this issue, and I personally think that the new value is a good compromise. Thanks again @mhartington 😎
